window.generatedSongs = [
    { id: 1000, artist: 'Unknown Artist', title: '4U', genre: 'House1', votes: 0 },
    { id: 1001, artist: 'Unknown Artist', title: 'A Fire Inside Of Me', genre: 'House1', votes: 0 },
    { id: 1002, artist: 'Unknown Artist', title: 'All Day All Night', genre: 'House1', votes: 0 },
    { id: 1003, artist: 'Around the World', title: 'Radio Edit Radio Edit', genre: 'House1', votes: 0 },
    { id: 1004, artist: 'Unknown Artist', title: 'Ask Me', genre: 'House1', votes: 0 },
    { id: 1005, artist: 'Unknown Artist', title: 'At Night I Think Of You', genre: 'House1', votes: 0 },
    { id: 1006, artist: 'Unknown Artist', title: 'Baby Girl', genre: 'House1', votes: 0 },
    { id: 1007, artist: 'Back to You', title: 'Fourth Co Remix', genre: 'House1', votes: 0 },
    { id: 1008, artist: 'Unknown Artist', title: 'Baddy On The Floor', genre: 'House1', votes: 0 },
    { id: 1009, artist: 'Unknown Artist', title: 'Beat Goes On Rhythm to the Brain', genre: 'House1', votes: 0 },
    { id: 1010, artist: 'Unknown Artist', title: 'Bitch Dont Kill My Vibe', genre: 'House1', votes: 0 },
    { id: 1011, artist: 'Brat vs Demure', title: 'Extended Mix', genre: 'House1', votes: 0 },
    { id: 1012, artist: 'Unknown Artist', title: 'Brat vs Demure', genre: 'House1', votes: 0 },
    { id: 1013, artist: 'Unknown Artist', title: 'Bulla', genre: 'House1', votes: 0 },
    { id: 1014, artist: 'Unknown Artist', title: 'Diamonds On My Mind', genre: 'House1', votes: 0 },
    { id: 1015, artist: 'Unknown Artist', title: 'Dirty Cash Money Talks', genre: 'House1', votes: 0 },
    { id: 1016, artist: 'Unknown Artist', title: 'Edge of Seventeen', genre: 'House1', votes: 0 },
    { id: 1017, artist: 'Fazer Lazer', title: 'Radio Edit', genre: 'House1', votes: 0 },
    { id: 1018, artist: 'Finally', title: '12 Choice Mix', genre: 'House1', votes: 0 },
    { id: 1019, artist: 'Unknown Artist', title: 'Free Your Body', genre: 'House1', votes: 0 },
    { id: 1020, artist: 'Unknown Artist', title: 'FUNKUMEAN', genre: 'House1', votes: 0 },
    { id: 1021, artist: 'Gas Pedal', title: 'Kyle Watson Remix', genre: 'House1', votes: 0 },
    { id: 1022, artist: 'Unknown Artist', title: 'Get Silly', genre: 'House1', votes: 0 },
    { id: 1023, artist: 'Unknown Artist', title: 'Gettin Heard', genre: 'House1', votes: 0 },
    { id: 1024, artist: 'Unknown Artist', title: 'Girl', genre: 'House1', votes: 0 },
    { id: 1025, artist: 'Unknown Artist', title: 'Girls Dont Like Sleep', genre: 'House1', votes: 0 },
    { id: 1026, artist: 'Unknown Artist', title: 'Give Her Right Back ft Dances With White Girls', genre: 'House1', votes: 0 },
    { id: 1027, artist: 'Goodums', title: 'Sammy Virji Remix', genre: 'House1', votes: 0 },
    { id: 1028, artist: 'Unknown Artist', title: 'Gorilla', genre: 'House1', votes: 0 },
    { id: 1029, artist: 'Unknown Artist', title: 'Groovin', genre: 'House1', votes: 0 },
    { id: 1030, artist: 'Unknown Artist', title: 'Happy Feelings', genre: 'House1', votes: 0 },
    { id: 1031, artist: 'Unknown Artist', title: 'Happy Music', genre: 'House1', votes: 0 },
    { id: 1032, artist: 'Unknown Artist', title: 'Hello Salutations', genre: 'House1', votes: 0 },
    { id: 1033, artist: 'Unknown Artist', title: 'Hi Life', genre: 'House1', votes: 0 },
    { id: 1034, artist: 'Unknown Artist', title: 'Hornie', genre: 'House1', votes: 0 },
    { id: 1035, artist: 'Unknown Artist', title: 'Horny', genre: 'House1', votes: 0 },
    { id: 1036, artist: 'I Only Smoke When I Drink', title: 'Claptone Remix', genre: 'House1', votes: 0 },
    { id: 1037, artist: 'I Remember', title: 'John Summit Remix', genre: 'House1', votes: 0 },
    { id: 1038, artist: 'Unknown Artist', title: 'I See Colors', genre: 'House1', votes: 0 },
    { id: 1039, artist: 'Unknown Artist', title: 'I Will Survive', genre: 'House1', votes: 0 },
    { id: 1040, artist: 'In The Air Tonight', title: 'Amal Nemer Remix', genre: 'House1', votes: 0 },
    { id: 1041, artist: 'Unknown Artist', title: 'Its Not Right But Its Okay', genre: 'House1', votes: 0 },
    { id: 1042, artist: 'Its That Time', title: 'FISHER Remix', genre: 'House1', votes: 0 },
    { id: 1043, artist: 'James Hype & Major Lazer', title: 'Number 1 (Bennie Edit)', genre: 'House1', votes: 0 },
    { id: 1044, artist: 'Unknown Artist', title: 'Jealous', genre: 'House1', votes: 0 },
    { id: 1045, artist: 'Unknown Artist', title: 'Jerk It Out', genre: 'House1', votes: 0 },
    { id: 1046, artist: 'Lady', title: 'Hear Me Tonight', genre: 'House1', votes: 0 },
    { id: 1047, artist: 'Unknown Artist', title: 'Last Night', genre: 'House1', votes: 0 },
    { id: 1048, artist: 'Leave The World Behind', title: 'Radio Edit', genre: 'House1', votes: 0 },
    { id: 1049, artist: 'LETS DO IT AGAIN', title: 'Radio Edit', genre: 'House1', votes: 0 },
    { id: 1050, artist: 'Unknown Artist', title: 'Life', genre: 'House1', votes: 0 },
    { id: 1051, artist: 'Unknown Artist', title: 'Lovely Day 2k24', genre: 'House1', votes: 0 },
    { id: 1052, artist: 'Unknown Artist', title: 'Make U Sweat', genre: 'House1', votes: 0 },
    { id: 1053, artist: 'Unknown Artist', title: 'Move On Up Mark Knight Remix', genre: 'House1', votes: 0 },
    { id: 1054, artist: 'Murder On The Dancefloor', title: 'UKG Edit', genre: 'House1', votes: 0 },
    { id: 1055, artist: 'Music Sounds Better With You', title: 'Radio Edit', genre: 'House1', votes: 0 },
    { id: 1056, artist: 'Unknown Artist', title: 'My Body', genre: 'House1', votes: 0 },
    { id: 1057, artist: 'Unknown Artist', title: 'NAPSTER', genre: 'House1', votes: 0 },
    { id: 1058, artist: 'Unknown Artist', title: 'Needle On The Record', genre: 'House1', votes: 0 },
    { id: 1059, artist: 'Unknown Artist', title: 'Never Walk Alone', genre: 'House1', votes: 0 },
    { id: 1060, artist: 'Nobody Else', title: 'A-Trak Remix', genre: 'House1', votes: 0 },
    { id: 1061, artist: 'Paradise', title: 'Original Mix', genre: 'House1', votes: 0 },
    { id: 1062, artist: 'PATT Party All The Time', title: 'Adam Beyer Layton Giordani  Green Velvet Extended Remix', genre: 'House1', votes: 0 },
    { id: 1063, artist: 'Percolator', title: 'Chris Lake Remix', genre: 'House1', votes: 0 },
    { id: 1064, artist: 'Unknown Artist', title: 'Perfect Exceeder', genre: 'House1', votes: 0 },
    { id: 1065, artist: 'Unknown Artist', title: 'Pretty Boy Swag', genre: 'House1', votes: 0 },
    { id: 1066, artist: 'Unknown Artist', title: 'Relax My Eyes', genre: 'House1', votes: 0 },
    { id: 1067, artist: 'Unknown Artist', title: 'Run Away', genre: 'House1', votes: 0 },
    { id: 1068, artist: 'Samba Do Brasil', title: 'Radio Edit', genre: 'House1', votes: 0 },
    { id: 1069, artist: 'Satisfaction', title: 'Uk Radio Edit', genre: 'House1', votes: 0 },
    { id: 1070, artist: 'Unknown Artist', title: 'Save My Life', genre: 'House1', votes: 0 },
    { id: 1071, artist: 'Unknown Artist', title: 'Saving Up', genre: 'House1', votes: 0 },
    { id: 1072, artist: 'Unknown Artist', title: 'Say My Name', genre: 'House1', votes: 0 },
    { id: 1073, artist: 'Unknown Artist', title: 'Shes Gone Dance On', genre: 'House1', votes: 0 },
    { id: 1074, artist: 'Unknown Artist', title: 'Sidewindah feat Flirta D', genre: 'House1', votes: 0 },
    { id: 1075, artist: 'Unknown Artist', title: 'Sippin Yak', genre: 'House1', votes: 0 },
    { id: 1076, artist: 'Unknown Artist', title: 'Smooth Operator', genre: 'House1', votes: 0 },
    { id: 1077, artist: 'Unknown Artist', title: 'Snake', genre: 'House1', votes: 0 },
    { id: 1078, artist: 'Unknown Artist', title: 'Somebody 2024', genre: 'House1', votes: 0 },
    { id: 1079, artist: 'Space Jam Jay Pryor Remix', title: 'Radio Mix', genre: 'House1', votes: 0 },
    { id: 1080, artist: 'Unknown Artist', title: 'Stephanie', genre: 'House1', votes: 0 },
    { id: 1081, artist: 'Unknown Artist', title: 'Still Sleepless', genre: 'House1', votes: 0 },
    { id: 1082, artist: 'Stop This Flame', title: 'Celeste x MK', genre: 'House1', votes: 0 },
    { id: 1083, artist: 'Unknown Artist', title: 'summer on the inside', genre: 'House1', votes: 0 },
    { id: 1084, artist: 'Unknown Artist', title: 'Super Pop Song Not Depressing', genre: 'House1', votes: 0 },
    { id: 1085, artist: 'Unknown Artist', title: 'Take Ya B', genre: 'House1', votes: 0 },
    { id: 1086, artist: 'The Days', title: 'NOTION Remix', genre: 'House1', votes: 0 },
    { id: 1087, artist: 'The Less I know The Better', title: 'Remix', genre: 'House1', votes: 0 },
    { id: 1088, artist: 'Unknown Artist', title: 'This Is Your Night', genre: 'House1', votes: 0 },
    { id: 1089, artist: 'Those Days', title: 'Original Mix', genre: 'House1', votes: 0 },
    { id: 1090, artist: 'Unknown Artist', title: 'To The Beat', genre: 'House1', votes: 0 },
    { id: 1091, artist: 'Unknown Artist', title: 'Toi Et Moi', genre: 'House1', votes: 0 },
    { id: 1092, artist: 'Unknown Artist', title: 'TV DREAMS', genre: 'House1', votes: 0 },
    { id: 1093, artist: 'Unknown Artist', title: 'U Should Not Be Doing That', genre: 'House1', votes: 0 },
    { id: 1094, artist: 'Unknown Artist', title: 'Upside Down', genre: 'House1', votes: 0 },
    { id: 1095, artist: 'Unknown Artist', title: 'Valerie', genre: 'House1', votes: 0 },
    { id: 1096, artist: 'Unknown Artist', title: 'Vent', genre: 'House1', votes: 0 },
    { id: 1097, artist: 'Unknown Artist', title: 'Vogue', genre: 'House1', votes: 0 },
    { id: 1098, artist: 'Unknown Artist', title: 'Waiting For Tonight', genre: 'House1', votes: 0 },
    { id: 1099, artist: 'Unknown Artist', title: 'WAX MAGNER', genre: 'House1', votes: 0 },
    { id: 1100, artist: 'World Hold On', title: 'FISHER Rework', genre: 'House1', votes: 0 },
    { id: 1101, artist: 'Unknown Artist', title: '01 Jungle book.wav', genre: 'MyMix', votes: 0 },
    { id: 1102, artist: 'Unknown Artist', title: '01 Mini mix 1 v2', genre: 'MyMix', votes: 0 },
    { id: 1103, artist: 'Unknown Artist', title: '01 Mini mix 1', genre: 'MyMix', votes: 0 },
    { id: 1104, artist: 'Unknown Artist', title: '01 Mini mix Deep  tech house', genre: 'MyMix', votes: 0 },
    { id: 1105, artist: '01 Mini mix HardTech', title: 'Hardstyle', genre: 'MyMix', votes: 0 },
    { id: 1106, artist: 'Unknown Artist', title: '01 Mix n3', genre: 'MyMix', votes: 0 },
    { id: 1107, artist: 'Unknown Artist', title: '01 PsyTrance 1', genre: 'MyMix', votes: 0 },
    { id: 1108, artist: 'Unknown Artist', title: '01 Random no preparation', genre: 'MyMix', votes: 0 },
    { id: 1109, artist: 'Unknown Artist', title: '01 Sunset beach vibes', genre: 'MyMix', votes: 0 },
    { id: 1110, artist: 'Unknown Artist', title: '01 Transi test', genre: 'MyMix', votes: 0 },
    { id: 1111, artist: 'Alan Walker', title: 'The Spectre', genre: 'House', votes: 0 },
    { id: 1112, artist: 'Disco Lines & Tinashe', title: 'No Broke Boys', genre: 'House', votes: 0 },
    { id: 1113, artist: 'Unknown Artist', title: 'Jack Back ‘(It Happens) Sometimes’', genre: 'House', votes: 0 },
    { id: 1114, artist: 'Julio Navas, Gustavo Bravetti & David Amo', title: 'Raw (Tony Romera Remix)', genre: 'House', votes: 0 },
    { id: 1115, artist: 'La Fuente', title: 'I Want You', genre: 'House', votes: 0 },
    { id: 1116, artist: 'La Fuente', title: 'Lights Out', genre: 'House', votes: 0 },
    { id: 1117, artist: 'Matt Sassari, CHRSTPHR & Barbatuques', title: 'Baiana (Extended Mix)', genre: 'House', votes: 0 },
    { id: 1118, artist: 'Milani Deeper', title: 'Shake That', genre: 'House', votes: 0 },
    { id: 1119, artist: 'Rick Wayne', title: 'Praise The Lord', genre: 'House', votes: 0 },
    { id: 1120, artist: 'Vicetone', title: 'Nevada (ft. Cozi Zuehlsdorff)', genre: 'House', votes: 0 },
    { id: 1121, artist: 'Control Alt Delete & Don Diablo', title: 'Maniac', genre: 'D&B', votes: 0 },
    { id: 1122, artist: 'Control Alt Delete, Kris Kiss & T & Sugah', title: 'The Formula', genre: 'D&B', votes: 0 },
    { id: 1123, artist: 'Culture Shock, Sub Focus & Fragma', title: 'Miracle', genre: 'D&B', votes: 0 },
    { id: 1124, artist: 'Dimension & Sub Focus', title: 'Desire', genre: 'D&B', votes: 0 },
    { id: 1125, artist: 'Disco Lines & Tinashe', title: 'No Broke Boys', genre: 'D&B', votes: 0 },
    { id: 1126, artist: 'Pendulum, Rob Swire & Armin van Buuren', title: 'Sound of You', genre: 'D&B', votes: 0 },
    { id: 1127, artist: 'SOFI & Crankdat', title: 'Whiplash', genre: 'D&B', votes: 0 },
    { id: 1128, artist: 'T & Sugah', title: 'Danger', genre: 'D&B', votes: 0 },
    { id: 1129, artist: 'T & Sugah', title: 'Lose Control (ft. Grace Barton)', genre: 'D&B', votes: 0 },
    { id: 1130, artist: 'Alan Walker', title: 'The Spectre', genre: 'House extract', votes: 0 },
    { id: 1131, artist: 'Disco Lines & Tinashe', title: 'No Broke Boys', genre: 'House extract', votes: 0 },
    { id: 1132, artist: 'Unknown Artist', title: 'Gettin Heard', genre: 'House extract', votes: 0 },
    { id: 1133, artist: 'Unknown Artist', title: 'Horny', genre: 'House extract', votes: 0 },
    { id: 1134, artist: 'I Only Smoke When I Drink', title: 'Claptone Remix', genre: 'House extract', votes: 0 },
    { id: 1135, artist: 'Unknown Artist', title: 'Jack Back ‘(It Happens) Sometimes’', genre: 'House extract', votes: 0 },
    { id: 1136, artist: 'Julio Navas, Gustavo Bravetti & David Amo', title: 'Raw (Tony Romera Remix)', genre: 'House extract', votes: 0 },
    { id: 1137, artist: 'La Fuente', title: 'I Want You', genre: 'House extract', votes: 0 },
    { id: 1138, artist: 'La Fuente', title: 'Lights Out', genre: 'House extract', votes: 0 },
    { id: 1139, artist: 'Unknown Artist', title: 'Love Regenerator', genre: 'House extract', votes: 0 },
    { id: 1140, artist: 'Matt Sassari, CHRSTPHR & Barbatuques', title: 'Baiana (Extended Mix)', genre: 'House extract', votes: 0 },
    { id: 1141, artist: 'Milani Deeper', title: 'Shake That', genre: 'House extract', votes: 0 },
    { id: 1142, artist: 'Unknown Artist', title: 'Needle On The Record', genre: 'House extract', votes: 0 },
    { id: 1143, artist: 'Rick Wayne', title: 'Praise The Lord', genre: 'House extract', votes: 0 },
    { id: 1144, artist: 'Unknown Artist', title: 'Take Ya B', genre: 'House extract', votes: 0 },
    { id: 1145, artist: 'Those Days', title: 'Original Mix', genre: 'House extract', votes: 0 },
    { id: 1146, artist: 'Unknown Artist', title: 'TV DREAMS', genre: 'House extract', votes: 0 },
    { id: 1147, artist: 'Unknown Artist', title: 'U Should Not Be Doing That', genre: 'House extract', votes: 0 },
    { id: 1148, artist: 'Vicetone', title: 'Nevada (ft. Cozi Zuehlsdorff)', genre: 'House extract', votes: 0 },
    { id: 1149, artist: 'Unknown Artist', title: 'videoplayback', genre: 'House extract', votes: 0 },
    { id: 1150, artist: 'Unknown Artist', title: 'Waiting For Tonight', genre: 'House extract', votes: 0 },
    { id: 1151, artist: 'Unknown Artist', title: 'Are You With Me (Calvo Extended Remix)', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1152, artist: 'Unknown Artist', title: 'Beauty Queen', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1153, artist: 'BLV', title: 'Lion King (2006 Remix)  Heb Lyrics', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1154, artist: 'Gabry Ponte, Steve Aoki, KEL', title: 'He\'s A Pirate (Save Me) [Official Visualizer]', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1155, artist: 'Unknown Artist', title: 'Golden (feat. Blondfire)', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1156, artist: 'Unknown Artist', title: 'Juicy M & MZRIN  Take Control', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1157, artist: 'Monocule & LAMAS (BR)', title: 'Your Eyes (Extended Mix)', genre: 'Tech House - Hardstyle mix', votes: 0 },
    { id: 1158, artist: 'Unknown Artist', title: '01 -Szikra', genre: 'Beach party', votes: 0 },
    { id: 1159, artist: '02', title: 'Slow Down - VintageCulture & Slow Motion Remix', genre: 'Beach party', votes: 0 },
    { id: 1160, artist: '03', title: 'OutTheFireAtTheHotel - Franky_Rizardo__Ros_T_feat._Eunice_Collins', genre: 'Beach party', votes: 0 },
    { id: 1161, artist: '04', title: 'Tutti Flutti', genre: 'Beach party', votes: 0 },
    { id: 1162, artist: '05', title: 'Illusion - Honey Dijon Remix', genre: 'Beach party', votes: 0 },
    { id: 1163, artist: '06', title: 'Hugel GROSSOMODDO - Andalucia', genre: 'Beach party', votes: 0 },
    { id: 1164, artist: 'Go Back (feat. Julia Church)', title: 'John Summit', genre: 'Beach party', votes: 0 },
    { id: 1165, artist: 'Pretty Low (Galantis & BULLI VIP Mix)', title: 'Dillon Francis', genre: 'Beach party', votes: 0 },
    { id: 1166, artist: 'Control Alt Delete & Don Diablo', title: 'Maniac', genre: 'Drum & Bass', votes: 0 },
    { id: 1167, artist: 'Control Alt Delete, Kris Kiss & T & Sugah', title: 'The Formula', genre: 'Drum & Bass', votes: 0 },
    { id: 1168, artist: 'Culture Shock, Sub Focus & Fragma', title: 'Miracle', genre: 'Drum & Bass', votes: 0 },
    { id: 1169, artist: 'Dimension & Sub Focus', title: 'Desire', genre: 'Drum & Bass', votes: 0 },
    { id: 1170, artist: 'Disco Lines & Tinashe', title: 'No Broke Boys', genre: 'Drum & Bass', votes: 0 },
    { id: 1171, artist: 'Pendulum, Rob Swire & Armin van Buuren', title: 'Sound of You', genre: 'Drum & Bass', votes: 0 },
    { id: 1172, artist: 'SOFI & Crankdat', title: 'Whiplash', genre: 'Drum & Bass', votes: 0 },
    { id: 1173, artist: 'T & Sugah', title: 'Danger', genre: 'Drum & Bass', votes: 0 },
    { id: 1174, artist: 'T & Sugah', title: 'Lose Control (ft. Grace Barton)', genre: 'Drum & Bass', votes: 0 },
    { id: 1175, artist: 'BEAUZ & XYSM', title: 'Bella Ciao [Monstercat Release]', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1176, artist: 'BEAUZ x NOYSE x Datti', title: 'Come On Baddie Let\'s Go Party', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1177, artist: 'Unknown Artist', title: 'Bel Mercy (BEAUZ Hard Techno Remix) feat. Nokia', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1178, artist: 'Black Eyed Peas', title: 'My Humps (BEAUZ Hard Techno Remix)', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1179, artist: 'Unknown Artist', title: 'Gigi D\'Agostino Bla Bla Bla', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1180, artist: 'Unknown Artist', title: 'Kernkraft 400 (Hardstyle Remix)', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1181, artist: 'Unknown Artist', title: 'LICK IT (Official Visualizer)', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1182, artist: 'Luca Testa & The FifthGuys', title: 'Quèdate (Feat. Polina Grace) [Hardstyle Remix]', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1183, artist: 'Luca Testa', title: 'Hey Brother (Feat. Efi Gjika) [Hardstyle Remix]', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1184, artist: 'Luca Testa feat. Uneven', title: 'Hangover (Hardstyle Remix) [www.slider.kz]', genre: 'Hard Tech- Hardstyle', votes: 0 },
    { id: 1185, artist: 'Adem Bogoceli & Farenthide', title: 'Yimanya', genre: 'House Essentials', votes: 0 },
    { id: 1186, artist: 'Alaia & Gallo', title: 'Lipstick', genre: 'House Essentials', votes: 0 },
    { id: 1187, artist: 'Alex Now (ES)', title: 'Techno Vibes (feat. Nancie)', genre: 'House Essentials', votes: 0 },
    { id: 1188, artist: 'Almanac', title: 'Bounce For Me (Extended Mix)', genre: 'House Essentials', votes: 0 },
    { id: 1189, artist: 'Arianna Triassi', title: 'Te Catar (feat. MC PR & MC Pequeno Diamante)', genre: 'House Essentials', votes: 0 },
    { id: 1190, artist: 'Arundel', title: 'CTRL', genre: 'House Essentials', votes: 0 },
    { id: 1191, artist: 'Astrohertz', title: 'Hold Me', genre: 'House Essentials', votes: 0 },
    { id: 1192, artist: 'Avi Sic & AK Renny', title: 'Down Low', genre: 'House Essentials', votes: 0 },
    { id: 1193, artist: 'Boothed', title: 'When You Touch', genre: 'House Essentials', votes: 0 },
    { id: 1194, artist: 'Breathe Carolina & Sunstars', title: 'Lightspeed', genre: 'House Essentials', votes: 0 },
    { id: 1195, artist: 'Brian Cross & Joyse', title: 'GOOTF', genre: 'House Essentials', votes: 0 },
    { id: 1196, artist: 'Chester Young & Hackatone', title: 'Genesis (Don Diablo Edit) (feat. SUVI)', genre: 'House Essentials', votes: 0 },
    { id: 1197, artist: 'Chris Lake & Odd Mob', title: 'Ease My Mind (Odd Mob Remix)', genre: 'House Essentials', votes: 0 },
    { id: 1198, artist: 'Chris Lake', title: 'Savana', genre: 'House Essentials', votes: 0 },
    { id: 1199, artist: 'Chris Lorenzo', title: 'Appetite', genre: 'House Essentials', votes: 0 },
    { id: 1200, artist: 'Chris Lorenzo, Max Styler & Audio Bullys', title: 'London\'s On Fire', genre: 'House Essentials', votes: 0 },
    { id: 1201, artist: 'CID', title: 'Creepin\'', genre: 'House Essentials', votes: 0 },
    { id: 1202, artist: 'Control Room & Dashi', title: 'What\'s Your Motive', genre: 'House Essentials', votes: 0 },
    { id: 1203, artist: 'Danell Arma & Noro', title: 'Family Affair', genre: 'House Essentials', votes: 0 },
    { id: 1204, artist: 'Dark Heart', title: 'Damn Good', genre: 'House Essentials', votes: 0 },
    { id: 1205, artist: 'DJ Licious & Mingue', title: '911', genre: 'House Essentials', votes: 0 },
    { id: 1206, artist: 'Don Diablo & MK', title: 'Next To Me (feat. Gaby Gerlis)', genre: 'House Essentials', votes: 0 },
    { id: 1207, artist: 'Don Diablo & Nelly Furtado', title: 'Doing Nothin\'', genre: 'House Essentials', votes: 0 },
    { id: 1208, artist: 'Don Diablo & Qobra', title: 'Remember Me', genre: 'House Essentials', votes: 0 },
    { id: 1209, artist: 'Don Diablo & Tseba', title: 'The Devil Works Hard', genre: 'House Essentials', votes: 0 },
    { id: 1210, artist: 'Don Diablo', title: 'Freek Like Me', genre: 'House Essentials', votes: 0 },
    { id: 1211, artist: 'Don Diablo', title: 'SexyBack', genre: 'House Essentials', votes: 0 },
    { id: 1212, artist: 'Don Diablo', title: 'The Way I Are', genre: 'House Essentials', votes: 0 },
    { id: 1213, artist: 'Ely Oaks & Eric Spike', title: 'Crossroads', genre: 'House Essentials', votes: 0 },
    { id: 1214, artist: 'ESCARGOT & SNAILS', title: 'HOUSE PARTY', genre: 'House Essentials', votes: 0 },
    { id: 1215, artist: 'Filip Grönlund', title: 'Rails', genre: 'House Essentials', votes: 0 },
    { id: 1216, artist: 'Firebeatz & Noise Cans', title: 'Selecta', genre: 'House Essentials', votes: 0 },
    { id: 1217, artist: 'FISHER & bbyclose', title: 'Blackberries', genre: 'House Essentials', votes: 0 },
    { id: 1218, artist: 'FISHER', title: 'Stay', genre: 'House Essentials', votes: 0 },
    { id: 1219, artist: 'Fletcher Kerr', title: 'Stay Connected', genre: 'House Essentials', votes: 0 },
    { id: 1220, artist: 'G-POL', title: 'Renegade Master (Don Diablo Edit)', genre: 'House Essentials', votes: 0 },
    { id: 1221, artist: 'Goshfather', title: 'Where Were U', genre: 'House Essentials', votes: 0 },
    { id: 1222, artist: 'Guy Mac', title: 'Divine Call', genre: 'House Essentials', votes: 0 },
    { id: 1223, artist: 'Hatiras', title: 'Hypnotized', genre: 'House Essentials', votes: 0 },
    { id: 1224, artist: 'HAWK., Penn Brothers & Jaydan Wolf', title: 'Inside', genre: 'House Essentials', votes: 0 },
    { id: 1225, artist: 'Ian G', title: 'Body Highs (feat. Krysta Youngs)', genre: 'House Essentials', votes: 0 },
    { id: 1226, artist: 'Jack Orley', title: 'Don\'t Stop', genre: 'House Essentials', votes: 0 },
    { id: 1227, artist: 'Jaded, Black Caviar & Antony & Cleopatra', title: 'Slippin\'', genre: 'House Essentials', votes: 0 },
    { id: 1228, artist: 'Jake Silva & Frankie Sims', title: 'New Phone Who Dis', genre: 'House Essentials', votes: 0 },
    { id: 1229, artist: 'JLV & Kazhi', title: 'Make Out', genre: 'House Essentials', votes: 0 },
    { id: 1230, artist: 'JLV', title: 'SWEAT', genre: 'House Essentials', votes: 0 },
    { id: 1231, artist: 'Joshwa & Enzo is Burning', title: 'Night Moves', genre: 'House Essentials', votes: 0 },
    { id: 1232, artist: 'Jude & Frank & Lohrasp Kansara', title: 'Curura', genre: 'House Essentials', votes: 0 },
    { id: 1233, artist: 'Kayote & The Galaxy', title: 'Rakata', genre: 'House Essentials', votes: 0 },
    { id: 1234, artist: 'KuKs', title: 'Get Ready', genre: 'House Essentials', votes: 0 },
    { id: 1235, artist: 'KuKs', title: 'Taste', genre: 'House Essentials', votes: 0 },
    { id: 1236, artist: 'Lemex & Sam Shelby', title: 'Thick', genre: 'House Essentials', votes: 0 },
    { id: 1237, artist: 'Linkin Park', title: 'Lost', genre: 'House Essentials', votes: 0 },
    { id: 1238, artist: 'Lion & Prime Punk', title: 'You Ready_!', genre: 'House Essentials', votes: 0 },
    { id: 1239, artist: 'LOVRA', title: 'Lick It', genre: 'House Essentials', votes: 0 },
    { id: 1240, artist: 'Low Blow & MÆDM', title: 'Connection', genre: 'House Essentials', votes: 0 },
    { id: 1241, artist: 'Malarkey', title: 'MONEY', genre: 'House Essentials', votes: 0 },
    { id: 1242, artist: 'Mat Frank', title: 'See Through You', genre: 'House Essentials', votes: 0 },
    { id: 1243, artist: 'Neon Steve & Black Caviar', title: 'Drug Test (feat. Tima Dee)', genre: 'House Essentials', votes: 0 },
    { id: 1244, artist: 'Nico Falla & No Trial', title: 'Closer', genre: 'House Essentials', votes: 0 },
    { id: 1245, artist: 'Niko The Kid', title: 'Atmosphere', genre: 'House Essentials', votes: 0 },
    { id: 1246, artist: 'NO SIGNE', title: 'From The Top (feat. HOSANNA)', genre: 'House Essentials', votes: 0 },
    { id: 1247, artist: 'PAJANE', title: 'MIND MADE UP', genre: 'House Essentials', votes: 0 },
    { id: 1248, artist: 'Prospa & Josh Baker', title: 'You Don\'t Own Me (feat. RAHH)', genre: 'House Essentials', votes: 0 },
    { id: 1249, artist: 'Quarterhead & Angel Janson', title: 'Out Of My Mind', genre: 'House Essentials', votes: 0 },
    { id: 1250, artist: 'REBRN & Oliver Marshak', title: 'Smash The Disco', genre: 'House Essentials', votes: 0 },
    { id: 1251, artist: 'Ryan Blyth & Duane Harden', title: 'Back To You (Don Diablo Edit)', genre: 'House Essentials', votes: 0 },
    { id: 1252, artist: 'Sam Collins & Jake Tarry', title: 'The Underground', genre: 'House Essentials', votes: 0 },
    { id: 1253, artist: 'SIDEPIECE & Bobby Shmurda', title: 'Cash Out', genre: 'House Essentials', votes: 0 },
    { id: 1254, artist: 'Siks', title: '5th Symphony', genre: 'House Essentials', votes: 0 },
    { id: 1255, artist: 'Sonny Fodera & Jazzy', title: 'All This Time', genre: 'House Essentials', votes: 0 },
    { id: 1256, artist: 'SUNGYOO', title: 'Move To The Rhythm', genre: 'House Essentials', votes: 0 },
    { id: 1257, artist: 'Tim Hox', title: 'Riddim', genre: 'House Essentials', votes: 0 },
    { id: 1258, artist: 'Tom Budin', title: 'The Function', genre: 'House Essentials', votes: 0 },
    { id: 1259, artist: 'Vato Gonzalez', title: 'Gypsy Riddim', genre: 'House Essentials', votes: 0 },
    { id: 1260, artist: 'Wahlstedt', title: 'Disconnected', genre: 'House Essentials', votes: 0 },
    { id: 1261, artist: 'Zonderling', title: 'Tunnel Vision (Don Diablo Edit)', genre: 'House Essentials', votes: 0 },
    { id: 1262, artist: 'Bleu Soleil & Luiza', title: 'Soleil Bleu', genre: 'Chai', votes: 0 },
    { id: 1263, artist: 'Charles Aznavour & Siks', title: 'La bohème', genre: 'Chai', votes: 0 },
    { id: 1264, artist: 'DJ Snake & Don Diablo', title: 'Let Me Love You (Don Diablo Remix) (feat. Justin Bieber)', genre: 'Chai', votes: 0 },
    { id: 1265, artist: 'Galantis, David Guetta & Little Mix', title: 'Heartbreak Anthem', genre: 'Chai', votes: 0 },
    { id: 1266, artist: 'Joe Dassin', title: 'Les Champs-Elysées', genre: 'Chai', votes: 0 },
    { id: 1267, artist: 'Joe Dassin', title: 'Siffler sur la colline', genre: 'Chai', votes: 0 },
    { id: 1268, artist: 'Oliver Heldens & Kate Ryan', title: 'Désenchantée (Oli’s EuroRave Mix)', genre: 'Chai', votes: 0 },
    { id: 1269, artist: 'Saint Perrier & Mark Diaz', title: 'Vintage Intro XX', genre: 'Chai', votes: 0 },
    { id: 1270, artist: 'Swedish House Mafia', title: 'Wait So Long', genre: 'Chai', votes: 0 },
    { id: 1271, artist: 'Astrix, Ritmo', title: 'Ziran Antinomy Remix', genre: 'PsyTrance', votes: 0 },
    { id: 1272, artist: 'Billx & Dr. Peacock', title: 'La Marche', genre: 'PsyTrance', votes: 0 },
    { id: 1273, artist: 'Billx & Ti K Ry', title: 'Bravery', genre: 'PsyTrance', votes: 0 },
    { id: 1274, artist: 'Blasterjaxx & Zafrir', title: 'Flying Dutchman', genre: 'PsyTrance', votes: 0 },
    { id: 1275, artist: 'Creeds', title: 'Push Up Slowboy Remix', genre: 'PsyTrance', votes: 0 },
    { id: 1276, artist: 'Dubdogz, Jetlag Music & Vitor Bueno', title: 'Atomic Bomb (feat. Juan Alcasar)', genre: 'PsyTrance', votes: 0 },
    { id: 1277, artist: 'Flash Jack', title: 'Kukeri', genre: 'PsyTrance', votes: 0 },
    { id: 1278, artist: 'Garmiani', title: 'AVA', genre: 'PsyTrance', votes: 0 },
    { id: 1279, artist: 'Henrique Camacho & Fatality', title: 'Sevilla', genre: 'PsyTrance', votes: 0 },
    { id: 1280, artist: 'HUTS, LUNAX & Jerome', title: 'Million Years (Jerome Edit)', genre: 'PsyTrance', votes: 0 },
    { id: 1281, artist: 'KSHMR & Zafrir', title: 'Winners Anthem', genre: 'PsyTrance', votes: 0 },
    { id: 1282, artist: 'Lanz', title: 'Shiva Tensei (Spectronikka Remix)', genre: 'PsyTrance', votes: 0 },
    { id: 1283, artist: 'le Shuuk', title: 'Goodbye (feat. Xillions)', genre: 'PsyTrance', votes: 0 },
    { id: 1284, artist: 'LOUD', title: '5 Billion Stars (Captain Hook Remix)', genre: 'PsyTrance', votes: 0 },
    { id: 1285, artist: 'Mike Candys', title: 'Darkness', genre: 'PsyTrance', votes: 0 },
    { id: 1286, artist: 'Neelix & Caroline Harrison', title: 'Makeup (Blazy Remix)', genre: 'PsyTrance', votes: 0 },
    { id: 1287, artist: 'Neelix & Durs', title: 'The Day We Met', genre: 'PsyTrance', votes: 0 },
    { id: 1288, artist: 'Neelix', title: 'Bang Bang (Sighter Remix)', genre: 'PsyTrance', votes: 0 },
    { id: 1289, artist: 'Neelix', title: 'Rebellion', genre: 'PsyTrance', votes: 0 },
    { id: 1290, artist: 'Neelix', title: 'Shadows', genre: 'PsyTrance', votes: 0 },
    { id: 1291, artist: 'NERVO & Skazi', title: 'Faded', genre: 'PsyTrance', votes: 0 },
    { id: 1292, artist: 'R3HAB & Gabry Ponte', title: 'The Portrait (Ooh La La), (lyrics)', genre: 'PsyTrance', votes: 0 },
    { id: 1293, artist: 'Sajanka & Terra', title: 'Galiya', genre: 'PsyTrance', votes: 0 },
    { id: 1294, artist: 'Sajanka & Whiteno1se', title: 'Anima Mea', genre: 'PsyTrance', votes: 0 },
    { id: 1295, artist: 'Sajanka', title: 'Oasis', genre: 'PsyTrance', votes: 0 },
    { id: 1296, artist: 'Sajanka', title: 'Sunny Dunny', genre: 'PsyTrance', votes: 0 },
    { id: 1297, artist: 'Talamasca', title: 'Lady Sweet Dream', genre: 'PsyTrance', votes: 0 },
    { id: 1298, artist: 'Tandava', title: 'Na Na Na', genre: 'PsyTrance', votes: 0 },
    { id: 1299, artist: 'Timmy Trumpet & Gabry Ponte', title: 'Mad World', genre: 'PsyTrance', votes: 0 },
    { id: 1300, artist: 'Timmy Trumpet & KSHMR', title: 'The Prayer (feat. Zafrir)', genre: 'PsyTrance', votes: 0 },
    { id: 1301, artist: 'Timmy Trumpet & Vini Vici', title: 'Thunder', genre: 'PsyTrance', votes: 0 },
    { id: 1302, artist: 'Timmy Trumpet & Vitas', title: 'The King', genre: 'PsyTrance', votes: 0 },
    { id: 1303, artist: 'Timmy Trumpet, Prezioso & 71 Digits', title: 'Three Little Birds', genre: 'PsyTrance', votes: 0 },
    { id: 1304, artist: 'Ummet Ozcan & Harris & Ford', title: 'Fight Back', genre: 'PsyTrance', votes: 0 },
    { id: 1305, artist: 'Ummet Ozcan, Charly Lownoise & Mental Theo & Orange INC', title: 'Wonderful Days', genre: 'PsyTrance', votes: 0 },
    { id: 1306, artist: 'Vini Vici, Neelix & MKLA', title: 'Come Close', genre: 'PsyTrance', votes: 0 },
    { id: 1307, artist: 'W&W', title: 'OIIA OIIA (Spinning Cat)', genre: 'PsyTrance', votes: 0 },
    { id: 1308, artist: '1D1R & Vacra', title: 'Balade', genre: 'POP FR', votes: 0 },
    { id: 1309, artist: 'Akhenaton & La Fonky Family', title: 'Bad Boys de Marseille, Pt. 2 (feat. Shurik\'n)', genre: 'POP FR', votes: 0 },
    { id: 1310, artist: 'Aya Nakamura & Joé Dwèt Filé', title: 'Baddies', genre: 'POP FR', votes: 0 },
    { id: 1311, artist: 'Aya Nakamura', title: 'Comportement', genre: 'POP FR', votes: 0 },
    { id: 1312, artist: 'Aya Nakamura', title: 'Copines', genre: 'POP FR', votes: 0 },
    { id: 1313, artist: 'Aya Nakamura', title: 'Djadja', genre: 'POP FR', votes: 0 },
    { id: 1314, artist: 'Aya Nakamura', title: 'Pookie', genre: 'POP FR', votes: 0 },
    { id: 1315, artist: 'Bande Organisée', title: 'SCH _ Kofs _ Jul _ Naps _ Soso Maness _ Elams _ Solda _ Houari __ Clip Officiel', genre: 'POP FR', votes: 0 },
    { id: 1316, artist: 'Bande Organisée 2', title: 'SCH _ Kofs _ JuL _ Alonzo _ Naps _ Soso Maness _ Elams _ Solda _ Houari __ 2024', genre: 'POP FR', votes: 0 },
    { id: 1317, artist: 'Barbara Pravi', title: 'Voilà', genre: 'POP FR', votes: 0 },
    { id: 1318, artist: 'Benab', title: 'Mon poto', genre: 'POP FR', votes: 0 },
    { id: 1319, artist: 'Bleu Soleil & Luiza', title: 'Soleil Bleu', genre: 'POP FR', votes: 0 },
    { id: 1320, artist: 'Booba', title: 'Saga', genre: 'POP FR', votes: 0 },
    { id: 1321, artist: 'Bouga', title: 'Belsunce Breakdown', genre: 'POP FR', votes: 0 },
    { id: 1322, artist: 'Bouss', title: 'Biff pas d\'love', genre: 'POP FR', votes: 0 },
    { id: 1323, artist: 'Céline Dion', title: 'Pour que tu m\'aimes encore', genre: 'POP FR', votes: 0 },
    { id: 1324, artist: 'Charles Aznavour', title: 'La bohème', genre: 'POP FR', votes: 0 },
    { id: 1325, artist: 'Charlotte Cardin', title: 'Feel Good', genre: 'POP FR', votes: 0 },
    { id: 1326, artist: 'Chinese Man', title: 'I\'ve got that tune', genre: 'POP FR', votes: 0 },
    { id: 1327, artist: 'Dadju', title: 'Jaloux', genre: 'POP FR', votes: 0 },
    { id: 1328, artist: 'Dadju', title: 'Reine', genre: 'POP FR', votes: 0 },
    { id: 1329, artist: 'Damso & Sarah Sey', title: 'Pa Pa Paw', genre: 'POP FR', votes: 0 },
    { id: 1330, artist: 'Darina Victry', title: 'Laisse moi t\'aimer', genre: 'POP FR', votes: 0 },
    { id: 1331, artist: 'Dhurata Dora', title: 'Zemër', genre: 'POP FR', votes: 0 },
    { id: 1332, artist: 'Djadja & Dinaz', title: 'Tu Sais', genre: 'POP FR', votes: 0 },
    { id: 1333, artist: 'Dr. Yaro', title: 'Minimum ça', genre: 'POP FR', votes: 0 },
    { id: 1334, artist: 'Fonky Family', title: 'Art de rue', genre: 'POP FR', votes: 0 },
    { id: 1335, artist: 'Fonky Family', title: 'Mystère et suspense', genre: 'POP FR', votes: 0 },
    { id: 1336, artist: 'GIMS & Damso', title: 'TU ME RENDS BÊTE', genre: 'POP FR', votes: 0 },
    { id: 1337, artist: 'Gims & DYSTINCT', title: 'SPIDER', genre: 'POP FR', votes: 0 },
    { id: 1338, artist: 'GIMS', title: '& La Mano 1.9 - PARISIENNE', genre: 'POP FR', votes: 0 },
    { id: 1339, artist: 'GIMS', title: 'AIR FORCE BLANCHE (feat. JUL)', genre: 'POP FR', votes: 0 },
    { id: 1340, artist: 'GIMS', title: 'APPELLE TA COPINE', genre: 'POP FR', votes: 0 },
    { id: 1341, artist: 'GIMS', title: 'Bella', genre: 'POP FR', votes: 0 },
    { id: 1342, artist: 'GIMS', title: 'Brisé (Pilule bleue)', genre: 'POP FR', votes: 0 },
    { id: 1343, artist: 'GIMS', title: 'Caméléon', genre: 'POP FR', votes: 0 },
    { id: 1344, artist: 'GIMS', title: 'CIEL', genre: 'POP FR', votes: 0 },
    { id: 1345, artist: 'GIMS', title: 'DO YOU LOVE ME _', genre: 'POP FR', votes: 0 },
    { id: 1346, artist: 'GIMS', title: 'Est-ce que tu m\'aimes _ (Pilule bleue)', genre: 'POP FR', votes: 0 },
    { id: 1347, artist: 'GIMS', title: 'J\'me tire', genre: 'POP FR', votes: 0 },
    { id: 1348, artist: 'GIMS', title: 'Le prix à payer', genre: 'POP FR', votes: 0 },
    { id: 1349, artist: 'GIMS', title: 'NINAO', genre: 'POP FR', votes: 0 },
    { id: 1350, artist: 'GIMS', title: 'OHMA TOKITA', genre: 'POP FR', votes: 0 },
    { id: 1351, artist: 'GIMS', title: 'Où aller', genre: 'POP FR', votes: 0 },
    { id: 1352, artist: 'GIMS', title: 'Sapés comme jamais (Pilule bleue) (feat. Niska)', genre: 'POP FR', votes: 0 },
    { id: 1353, artist: 'GIMS', title: 'SOIS PAS TIMIDE', genre: 'POP FR', votes: 0 },
    { id: 1354, artist: 'GIMS', title: 'Tu vas me manquer (Pilule bleue)', genre: 'POP FR', votes: 0 },
    { id: 1355, artist: 'Guy2Bezbar', title: 'Monaco', genre: 'POP FR', votes: 0 },
    { id: 1356, artist: 'Heuss L\'enfoiré', title: 'Moulaga (feat. JUL)', genre: 'POP FR', votes: 0 },
    { id: 1357, artist: 'Héritage, Dadju & Tayc', title: 'Épouse-moi', genre: 'POP FR', votes: 0 },
    { id: 1358, artist: 'Héritage, Dadju & Tayc', title: 'I love you', genre: 'POP FR', votes: 0 },
    { id: 1359, artist: 'IAM', title: 'Je danse le mia (Le Terrible Funk Remix) [Radio Edit] (Le Terrible Funk Remix; Radio Edit)', genre: 'POP FR', votes: 0 },
    { id: 1360, artist: 'IAM', title: 'Petit frère', genre: 'POP FR', votes: 0 },
    { id: 1361, artist: 'Indila', title: 'Dernière danse', genre: 'POP FR', votes: 0 },
    { id: 1362, artist: 'Indila', title: 'Love Story', genre: 'POP FR', votes: 0 },
    { id: 1363, artist: 'Indila', title: 'Tourner Dans Le Vide', genre: 'POP FR', votes: 0 },
    { id: 1364, artist: 'Jeck & Carla', title: 'M\'envoler', genre: 'POP FR', votes: 0 },
    { id: 1365, artist: 'Joé Dwèt Filé', title: '4 Kampé', genre: 'POP FR', votes: 0 },
    { id: 1366, artist: 'Joé Dwèt Filé', title: 'Jolie madame (feat. Ronisia)', genre: 'POP FR', votes: 0 },
    { id: 1367, artist: 'Joé Dwèt Filé', title: 'Slowly', genre: 'POP FR', votes: 0 },
    { id: 1368, artist: 'Josas', title: 'Pichichi', genre: 'POP FR', votes: 0 },
    { id: 1369, artist: 'JUL', title: 'J\'oublie tout', genre: 'POP FR', votes: 0 },
    { id: 1370, artist: 'JUL', title: 'On m\'appelle l\'ovni', genre: 'POP FR', votes: 0 },
    { id: 1371, artist: 'JUL', title: 'Wesh alors', genre: 'POP FR', votes: 0 },
    { id: 1372, artist: 'JUL, 13\'Organisé & L\'Algérino', title: 'Sous le soleil (feat. Sat, Fahar, Alonzo & Le Rat Luciano)', genre: 'POP FR', votes: 0 },
    { id: 1373, artist: 'K-Maro', title: 'Femme Like U', genre: 'POP FR', votes: 0 },
    { id: 1374, artist: 'KeBlack', title: 'Boucan (feat. Franglish)', genre: 'POP FR', votes: 0 },
    { id: 1375, artist: 'KeBlack', title: 'LAISSE MOI', genre: 'POP FR', votes: 0 },
    { id: 1376, artist: 'KeBlack', title: 'Melrose Place (feat. Guy2Bezbar)', genre: 'POP FR', votes: 0 },
    { id: 1377, artist: 'KeBlack', title: 'Mood', genre: 'POP FR', votes: 0 },
    { id: 1378, artist: 'Keny Arkana', title: 'Je me barre', genre: 'POP FR', votes: 0 },
    { id: 1379, artist: 'Khaled', title: 'C’est la vie', genre: 'POP FR', votes: 0 },
    { id: 1380, artist: 'L\'Algérino', title: 'Les menottes (Tching Tchang Tchong)', genre: 'POP FR', votes: 0 },
    { id: 1381, artist: 'L\'Algérino', title: 'Panama', genre: 'POP FR', votes: 0 },
    { id: 1382, artist: 'La Fouine', title: 'Ma Meilleure (feat. Zaho)', genre: 'POP FR', votes: 0 },
    { id: 1383, artist: 'Lartiste', title: 'Chocolat (feat. Awa Imani) (feat. Awa Imani)', genre: 'POP FR', votes: 0 },
    { id: 1384, artist: 'Linh', title: 'Je pense à vous', genre: 'POP FR', votes: 0 },
    { id: 1385, artist: 'Louane', title: 'Secret', genre: 'POP FR', votes: 0 },
    { id: 1386, artist: 'Lynda', title: 'Fini d’espérer', genre: 'POP FR', votes: 0 },
    { id: 1387, artist: 'Lynda', title: 'Passe ton chemin', genre: 'POP FR', votes: 0 },
    { id: 1388, artist: 'Marine', title: 'Ma faute', genre: 'POP FR', votes: 0 },
    { id: 1389, artist: 'Marwa Loud', title: 'Bad boy', genre: 'POP FR', votes: 0 },
    { id: 1390, artist: 'MHD', title: 'Bébé feat Dadju paroles lyrics', genre: 'POP FR', votes: 0 },
    { id: 1391, artist: 'Naps', title: 'Best life (feat. Gims)', genre: 'POP FR', votes: 0 },
    { id: 1392, artist: 'Naps', title: 'La kiffance', genre: 'POP FR', votes: 0 },
    { id: 1393, artist: 'Naza & SDM', title: 'Tout donner', genre: 'POP FR', votes: 0 },
    { id: 1394, artist: 'Nej', title: 'Paro', genre: 'POP FR', votes: 0 },
    { id: 1395, artist: 'Ninho', title: 'Lettre à une femme', genre: 'POP FR', votes: 0 },
    { id: 1396, artist: 'Niro', title: 'Qui sait _ (feat. ElGrandeToto)', genre: 'POP FR', votes: 0 },
    { id: 1397, artist: 'Psy 4 De La Rime', title: 'Le Temps D\'Un Instant', genre: 'POP FR', votes: 0 },
    { id: 1398, artist: 'SCH', title: 'Je la connais', genre: 'POP FR', votes: 0 },
    { id: 1399, artist: 'SDM', title: 'Bolide allemand', genre: 'POP FR', votes: 0 },
    { id: 1400, artist: 'Shay & Niska', title: 'Sans Coeur', genre: 'POP FR', votes: 0 },
    { id: 1401, artist: 'Slimane', title: 'Des milliers de je t\'aime (Paroles)', genre: 'POP FR', votes: 0 },
    { id: 1402, artist: 'Soolking & Gazo', title: 'Casanova', genre: 'POP FR', votes: 0 },
    { id: 1403, artist: 'Soolking & Ninho', title: 'C\'est Fort', genre: 'POP FR', votes: 0 },
    { id: 1404, artist: 'Soolking', title: 'CARRÉ OK (feat. GIMS)', genre: 'POP FR', votes: 0 },
    { id: 1405, artist: 'Soolking', title: 'Liberté (feat. Ouled El Bahdja)', genre: 'POP FR', votes: 0 },
    { id: 1406, artist: 'Soolking', title: 'Suavemente', genre: 'POP FR', votes: 0 },
    { id: 1407, artist: 'Soolking', title: 'Tour du monde (feat. L2B)', genre: 'POP FR', votes: 0 },
    { id: 1408, artist: 'Soprano', title: 'À la bien', genre: 'POP FR', votes: 0 },
    { id: 1409, artist: 'Soprano', title: 'Cosmo', genre: 'POP FR', votes: 0 },
    { id: 1410, artist: 'Soprano', title: 'En feu', genre: 'POP FR', votes: 0 },
    { id: 1411, artist: 'Soprano', title: 'Le coach (feat. Vincenzo)', genre: 'POP FR', votes: 0 },
    { id: 1412, artist: 'Soso Maness', title: 'Petrouchka (feat. PLK)', genre: 'POP FR', votes: 0 },
    { id: 1413, artist: 'Souf', title: 'Mi Amor', genre: 'POP FR', votes: 0 },
    { id: 1414, artist: 'Speak & Theo Rose', title: 'Amor, Amor (Radio Mix)', genre: 'POP FR', votes: 0 },
    { id: 1415, artist: 'Stefania', title: 'Empty without you (Radio Mix)', genre: 'POP FR', votes: 0 },
    { id: 1416, artist: 'Stromae', title: 'Alors on danse (Radio Edit)', genre: 'POP FR', votes: 0 },
    { id: 1417, artist: 'Stromae', title: 'Formidable', genre: 'POP FR', votes: 0 },
    { id: 1418, artist: 'Stromae', title: 'Papaoutai', genre: 'POP FR', votes: 0 },
    { id: 1419, artist: 'Stromae', title: 'Tous les mêmes', genre: 'POP FR', votes: 0 },
    { id: 1420, artist: 'Tayc', title: 'Forévà', genre: 'POP FR', votes: 0 },
    { id: 1421, artist: 'Tayc', title: 'Le temps', genre: 'POP FR', votes: 0 },
    { id: 1422, artist: 'Tayc', title: 'N\'y pense plus', genre: 'POP FR', votes: 0 },
    { id: 1423, artist: 'TKS 2G', title: 'Whine', genre: 'POP FR', votes: 0 },
    { id: 1424, artist: 'Vacra', title: 'Tiki Taka', genre: 'POP FR', votes: 0 },
    { id: 1425, artist: 'Vernis Rouge', title: 'Bande organisée', genre: 'POP FR', votes: 0 },
    { id: 1426, artist: 'Vitaa & Slimane', title: 'Avant toi', genre: 'POP FR', votes: 0 },
    { id: 1427, artist: 'Willy William', title: 'Ego (Radio Edit)', genre: 'POP FR', votes: 0 },
    { id: 1428, artist: 'Yanns', title: 'Clic clic pan pan', genre: 'POP FR', votes: 0 },
    { id: 1429, artist: 'Zaz', title: 'Je veux', genre: 'POP FR', votes: 0 },
    { id: 1430, artist: '50 Cent', title: 'In Da Club', genre: 'POP', votes: 0 },
    { id: 1431, artist: 'Aaron Smith & Krono', title: 'Dancin (Krono Remix) (feat. Luvli)', genre: 'POP', votes: 0 },
    { id: 1432, artist: 'Adam Port, Stryv, Keinemusik & Orso', title: 'Move', genre: 'POP', votes: 0 },
    { id: 1433, artist: 'Addison Rae', title: 'Diet Pepsi', genre: 'POP', votes: 0 },
    { id: 1434, artist: 'Adele', title: 'Rolling in the Deep', genre: 'POP', votes: 0 },
    { id: 1435, artist: 'Adele', title: 'Set Fire to the Rain', genre: 'POP', votes: 0 },
    { id: 1436, artist: 'Adele', title: 'Someone Like You', genre: 'POP', votes: 0 },
    { id: 1437, artist: 'Akon', title: 'Don\'t Matter', genre: 'POP', votes: 0 },
    { id: 1438, artist: 'Akon', title: 'Lonely', genre: 'POP', votes: 0 },
    { id: 1439, artist: 'Akon', title: 'Right Now (Na Na Na)', genre: 'POP', votes: 0 },
    { id: 1440, artist: 'Akon', title: 'Smack That (feat. Eminem)', genre: 'POP', votes: 0 },
    { id: 1441, artist: 'Alan Walker', title: 'Faded', genre: 'POP', votes: 0 },
    { id: 1442, artist: 'Alex Warren', title: 'Carry You Home', genre: 'POP', votes: 0 },
    { id: 1443, artist: 'Alex Warren', title: 'Eternity', genre: 'POP', votes: 0 },
    { id: 1444, artist: 'Alex Warren', title: 'Ordinary', genre: 'POP', votes: 0 },
    { id: 1445, artist: 'Alexandra Stan', title: 'Mr. Saxobeat (Radio Edit)', genre: 'POP', votes: 0 },
    { id: 1446, artist: 'Alicia Keys', title: 'Empire State of Mind (Part II) Broken Down', genre: 'POP', votes: 0 },
    { id: 1447, artist: 'Alicia Keys', title: 'Girl on Fire', genre: 'POP', votes: 0 },
    { id: 1448, artist: 'Alicia Keys', title: 'No One', genre: 'POP', votes: 0 },
    { id: 1449, artist: 'Amy Macdonald', title: 'This Is The Life', genre: 'POP', votes: 0 },
    { id: 1450, artist: 'Amy Winehouse', title: 'Back To Black', genre: 'POP', votes: 0 },
    { id: 1451, artist: 'Amy Winehouse', title: 'You Know I\'m No Good', genre: 'POP', votes: 0 },
    { id: 1452, artist: 'Anne-Marie', title: '2002', genre: 'POP', votes: 0 },
    { id: 1453, artist: 'Ariana Grande', title: '7 rings', genre: 'POP', votes: 0 },
    { id: 1454, artist: 'Ariana Grande', title: 'Side to Side (feat. Nicki Minaj)', genre: 'POP', votes: 0 },
    { id: 1455, artist: 'Ariana Grande', title: 'supernatural', genre: 'POP', votes: 0 },
    { id: 1456, artist: 'Ariana Grande', title: 'twilight zone', genre: 'POP', votes: 0 },
    { id: 1457, artist: 'Ariana Grande', title: 'we can\'t be friends (wait for your love)', genre: 'POP', votes: 0 },
    { id: 1458, artist: 'Artemas', title: 'i like the way you kiss me', genre: 'POP', votes: 0 },
    { id: 1459, artist: 'Ava Max', title: 'Sweet but Psycho', genre: 'POP', votes: 0 },
    { id: 1460, artist: 'Aventura', title: 'Obsesion (feat. Judy Santos)', genre: 'POP', votes: 0 },
    { id: 1461, artist: 'Avicii', title: 'Levels (Radio Edit)', genre: 'POP', votes: 0 },
    { id: 1462, artist: 'Avicii', title: 'Wake Me Up', genre: 'POP', votes: 0 },
    { id: 1463, artist: 'B.o.B', title: 'Airplanes (feat. Hayley Williams of Paramore)', genre: 'POP', votes: 0 },
    { id: 1464, artist: 'B.o.B', title: 'Nothin\' on You (feat. Bruno Mars)', genre: 'POP', votes: 0 },
    { id: 1465, artist: 'Benson Boone', title: 'Beautiful Things', genre: 'POP', votes: 0 },
    { id: 1466, artist: 'Benson Boone', title: 'Mystical Magical', genre: 'POP', votes: 0 },
    { id: 1467, artist: 'Beyoncé', title: 'Crazy In Love (feat. JAY-Z)', genre: 'POP', votes: 0 },
    { id: 1468, artist: 'Beyoncé', title: 'Halo', genre: 'POP', votes: 0 },
    { id: 1469, artist: 'Beyoncé', title: 'If I Were a Boy', genre: 'POP', votes: 0 },
    { id: 1470, artist: 'Beyoncé', title: 'Single Ladies (Put a Ring on It)', genre: 'POP', votes: 0 },
    { id: 1471, artist: 'Big Ali', title: 'WatiBigali (feat. Wati B)', genre: 'POP', votes: 0 },
    { id: 1472, artist: 'Billie Eilish & Khalid', title: 'lovely', genre: 'POP', votes: 0 },
    { id: 1473, artist: 'Billie Eilish', title: 'BIRDS OF A FEATHER', genre: 'POP', votes: 0 },
    { id: 1474, artist: 'Billie Eilish', title: 'CHIHIRO', genre: 'POP', votes: 0 },
    { id: 1475, artist: 'Billie Eilish', title: 'ocean eyes', genre: 'POP', votes: 0 },
    { id: 1476, artist: 'Billie Eilish', title: 'What Was I Made For_ [From The Motion Picture Barbie]', genre: 'POP', votes: 0 },
    { id: 1477, artist: 'Billie Eilish', title: 'WILDFLOWER', genre: 'POP', votes: 0 },
    { id: 1478, artist: 'Bon Jovi', title: 'It\'s My Life', genre: 'POP', votes: 0 },
    { id: 1479, artist: 'Brandy & Monica', title: 'The Boy Is Mine', genre: 'POP', votes: 0 },
    { id: 1480, artist: 'Britney Spears', title: 'Baby One More Time', genre: 'POP', votes: 0 },
    { id: 1481, artist: 'Britney Spears', title: 'Oops!...I Did It Again', genre: 'POP', votes: 0 },
    { id: 1482, artist: 'Britney Spears', title: 'Toxic', genre: 'POP', votes: 0 },
    { id: 1483, artist: 'Britney Spears', title: 'Womanizer', genre: 'POP', votes: 0 },
    { id: 1484, artist: 'Bruno Mars', title: 'Grenade', genre: 'POP', votes: 0 },
    { id: 1485, artist: 'Bruno Mars', title: 'Just the Way You Are', genre: 'POP', votes: 0 },
    { id: 1486, artist: 'Bruno Mars', title: 'Locked out of Heaven', genre: 'POP', votes: 0 },
    { id: 1487, artist: 'Bruno Mars', title: 'Marry You', genre: 'POP', votes: 0 },
    { id: 1488, artist: 'Bruno Mars', title: 'That\'s What I Like', genre: 'POP', votes: 0 },
    { id: 1489, artist: 'Bruno Mars', title: 'The Lazy Song', genre: 'POP', votes: 0 },
    { id: 1490, artist: 'Bruno Mars', title: 'Treasure', genre: 'POP', votes: 0 },
    { id: 1491, artist: 'BTS', title: 'Dynamite', genre: 'POP', votes: 0 },
    { id: 1492, artist: 'Calum Scott & Leona Lewis', title: 'You Are The Reason (Duet Version)', genre: 'POP', votes: 0 },
    { id: 1493, artist: 'Calvin Harris', title: 'Feel So Close (Radio Edit)', genre: 'POP', votes: 0 },
    { id: 1494, artist: 'Calvin Harris', title: 'I Need Your Love (feat. Ellie Goulding)', genre: 'POP', votes: 0 },
    { id: 1495, artist: 'Calvin Harris', title: 'Outside (feat. Ellie Goulding)', genre: 'POP', votes: 0 },
    { id: 1496, artist: 'Calvin Harris', title: 'Summer', genre: 'POP', votes: 0 },
    { id: 1497, artist: 'Calvin Harris', title: 'Thinking About You (feat. Ayah Marar)', genre: 'POP', votes: 0 },
    { id: 1498, artist: 'Capital Cities', title: 'Safe and Sound', genre: 'POP', votes: 0 },
    { id: 1499, artist: 'Carly Rae Jepsen', title: 'Call Me Maybe', genre: 'POP', votes: 0 },
    { id: 1500, artist: 'Chappell Roan', title: 'Good Luck, Babe!', genre: 'POP', votes: 0 },
    { id: 1501, artist: 'Chappell Roan', title: 'The Subway', genre: 'POP', votes: 0 },
    { id: 1502, artist: 'Charlie Puth', title: 'Attention', genre: 'POP', votes: 0 },
    { id: 1503, artist: 'Charlie Puth', title: 'We Don\'t Talk Anymore (feat. Selena Gomez)', genre: 'POP', votes: 0 },
    { id: 1504, artist: 'Chris Brown', title: 'Under The Influence', genre: 'POP', votes: 0 },
    { id: 1505, artist: 'Chris Brown', title: 'Yeah 3x', genre: 'POP', votes: 0 },
    { id: 1506, artist: 'Christina Perri', title: 'a thousand years', genre: 'POP', votes: 0 },
    { id: 1507, artist: 'Christophe Willem', title: 'Double je (Remix)', genre: 'POP', votes: 0 },
    { id: 1508, artist: 'Clean Bandit', title: 'Rather Be (feat. Jess Glynne)', genre: 'POP', votes: 0 },
    { id: 1509, artist: 'Clean Bandit', title: 'Rockabye (feat. Sean Paul & Anne-Marie)', genre: 'POP', votes: 0 },
    { id: 1510, artist: 'Coldplay', title: 'A Sky Full of Stars', genre: 'POP', votes: 0 },
    { id: 1511, artist: 'Coldplay', title: 'Adventure of a Lifetime', genre: 'POP', votes: 0 },
    { id: 1512, artist: 'Coldplay', title: 'Clocks', genre: 'POP', votes: 0 },
    { id: 1513, artist: 'Coldplay', title: 'Hymn for the Weekend', genre: 'POP', votes: 0 },
    { id: 1514, artist: 'Coldplay', title: 'Paradise', genre: 'POP', votes: 0 },
    { id: 1515, artist: 'Coldplay', title: 'Sparks', genre: 'POP', votes: 0 },
    { id: 1516, artist: 'Coldplay', title: 'The Scientist', genre: 'POP', votes: 0 },
    { id: 1517, artist: 'Coldplay', title: 'Viva La Vida', genre: 'POP', votes: 0 },
    { id: 1518, artist: 'Coldplay', title: 'Yellow', genre: 'POP', votes: 0 },
    { id: 1519, artist: 'Corbyn Besson & TZUYU', title: 'Blink', genre: 'POP', votes: 0 },
    { id: 1520, artist: 'd4vd', title: 'Romantic Homicide', genre: 'POP', votes: 0 },
    { id: 1521, artist: 'Daft Punk & Julian Casablancas', title: 'Instant Crush (feat. Julian Casablancas)', genre: 'POP', votes: 0 },
    { id: 1522, artist: 'Daft Punk', title: 'One More Time (Radio Edit)', genre: 'POP', votes: 0 },
    { id: 1523, artist: 'Daniel Powter', title: 'Bad Day', genre: 'POP', votes: 0 },
    { id: 1524, artist: 'David Guetta & Chris Willis', title: 'Gettin\' Over You (feat. Fergie & LMFAO)', genre: 'POP', votes: 0 },
    { id: 1525, artist: 'David Guetta & Sia', title: 'Beautiful People', genre: 'POP', votes: 0 },
    { id: 1526, artist: 'David Guetta', title: 'Memories (feat. Kid Cudi)', genre: 'POP', votes: 0 },
    { id: 1527, artist: 'David Guetta', title: 'Play Hard [New Edit] (feat. Akon & Ne-Yo)', genre: 'POP', votes: 0 },
    { id: 1528, artist: 'David Guetta', title: 'Sexy Bitch (feat. Akon)', genre: 'POP', votes: 0 },
    { id: 1529, artist: 'David Guetta', title: 'Titanium (feat. Sia)', genre: 'POP', votes: 0 },
    { id: 1530, artist: 'David Guetta', title: 'When Love Takes Over (feat. Kelly Rowland)', genre: 'POP', votes: 0 },
    { id: 1531, artist: 'David Guetta', title: 'Where Them Girls At (feat. Flo Rida & Nicki Minaj)', genre: 'POP', votes: 0 },
    { id: 1532, artist: 'David Guetta', title: 'Who\'s That Chick_ (feat. Rihanna)', genre: 'POP', votes: 0 },
    { id: 1533, artist: 'David Guetta', title: 'Without You (Radio Edit) (feat. Usher)', genre: 'POP', votes: 0 },
    { id: 1534, artist: 'David Kushner', title: 'Daylight', genre: 'POP', votes: 0 },
    { id: 1535, artist: 'DJ Antoine', title: 'Ma Chérie (DJ Antoine & Mad Mark 2K12 Radio Edit) (feat. The Beat Shakers)', genre: 'POP', votes: 0 },
    { id: 1536, artist: 'DJ Snake', title: 'Let Me Love You (feat. Justin Bieber)', genre: 'POP', votes: 0 },
    { id: 1537, artist: 'DJ Snake', title: 'Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)', genre: 'POP', votes: 0 },
    { id: 1538, artist: 'Doja Cat', title: 'Agora Hills', genre: 'POP', votes: 0 },
    { id: 1539, artist: 'Doja Cat', title: 'Paint The Town Red', genre: 'POP', votes: 0 },
    { id: 1540, artist: 'Dua Lipa', title: 'Dance The Night (From Barbie The Album)', genre: 'POP', votes: 0 },
    { id: 1541, artist: 'Dua Lipa', title: 'Houdini', genre: 'POP', votes: 0 },
    { id: 1542, artist: 'Dua Lipa', title: 'Illusion', genre: 'POP', votes: 0 },
    { id: 1543, artist: 'Dua Lipa', title: 'Levitating (feat. DaBaby)', genre: 'POP', votes: 0 },
    { id: 1544, artist: 'Dua Lipa', title: 'New Rules', genre: 'POP', votes: 0 },
    { id: 1545, artist: 'Dua Lipa', title: 'Training Season', genre: 'POP', votes: 0 },
    { id: 1546, artist: 'Duck Sauce, A-Trak & Armand Van Helden', title: 'Barbra Streisand (Radio Edit)', genre: 'POP', votes: 0 },
    { id: 1547, artist: 'Duke Dumont', title: 'I Got U (feat. Jax Jones)', genre: 'POP', votes: 0 },
    { id: 1548, artist: 'Duke Dumont', title: 'Ocean Drive', genre: 'POP', votes: 0 },
    { id: 1549, artist: 'Ed Sheeran', title: 'Azizam [Persian Version] (feat. Googoosh)', genre: 'POP', votes: 0 },
    { id: 1550, artist: 'Ed Sheeran', title: 'Dive', genre: 'POP', votes: 0 },
    { id: 1551, artist: 'Ed Sheeran', title: 'Perfect', genre: 'POP', votes: 0 },
    { id: 1552, artist: 'Ed Sheeran', title: 'Photograph', genre: 'POP', votes: 0 },
    { id: 1553, artist: 'Ed Sheeran', title: 'Sapphire', genre: 'POP', votes: 0 },
    { id: 1554, artist: 'Ed Sheeran', title: 'Shape of You', genre: 'POP', votes: 0 },
    { id: 1555, artist: 'Ed Sheeran', title: 'Thinking out Loud', genre: 'POP', votes: 0 },
    { id: 1556, artist: 'Eiffel 65', title: 'Blue (Da Ba Dee) (Video Edit)', genre: 'POP', votes: 0 },
    { id: 1557, artist: 'Ellie Goulding', title: 'Burn', genre: 'POP', votes: 0 },
    { id: 1558, artist: 'Eminem', title: 'Lose Yourself', genre: 'POP', votes: 0 },
    { id: 1559, artist: 'Eminem', title: 'Love The Way You Lie (feat. Rihanna)', genre: 'POP', votes: 0 },
    { id: 1560, artist: 'Eminem', title: 'Mockingbird', genre: 'POP', votes: 0 },
    { id: 1561, artist: 'Eminem', title: 'Not Afraid', genre: 'POP', votes: 0 },
    { id: 1562, artist: 'Eminem', title: 'The Real Slim Shady', genre: 'POP', votes: 0 },
    { id: 1563, artist: 'Eminem', title: 'Without Me', genre: 'POP', votes: 0 },
    { id: 1564, artist: 'Enrique Iglesias', title: 'Tired Of Being Sorry (Laisse Le Destin L\'Emporter) (Radio Edit) (feat. Nadiya)', genre: 'POP', votes: 0 },
    { id: 1565, artist: 'Evanescence', title: 'Bring Me To Life', genre: 'POP', votes: 0 },
    { id: 1566, artist: 'Far East Movement, The Cataracs & DEV', title: 'Like A G6', genre: 'POP', votes: 0 },
    { id: 1567, artist: 'Fifth Harmony', title: 'Work from Home (feat. Ty Dolla $ign)', genre: 'POP', votes: 0 },
    { id: 1568, artist: 'Flo Rida', title: 'Club Can\'t Handle Me (feat. David Guetta)', genre: 'POP', votes: 0 },
    { id: 1569, artist: 'Flo Rida', title: 'Good Feeling', genre: 'POP', votes: 0 },
    { id: 1570, artist: 'Flo Rida', title: 'Low (feat. T-Pain)', genre: 'POP', votes: 0 },
    { id: 1571, artist: 'Flo Rida', title: 'My House', genre: 'POP', votes: 0 },
    { id: 1572, artist: 'Flo Rida', title: 'Right Round (feat. Kesha)', genre: 'POP', votes: 0 },
    { id: 1573, artist: 'Flo Rida', title: 'Whistle', genre: 'POP', votes: 0 },
    { id: 1574, artist: 'Flo Rida', title: 'Wild Ones (feat. Sia)', genre: 'POP', votes: 0 },
    { id: 1575, artist: 'fun.', title: 'We Are Young (feat. Janelle Monáe)', genre: 'POP', votes: 0 },
    { id: 1576, artist: 'Gabriel Basco', title: 'The Last of Us', genre: 'POP', votes: 0 },
    { id: 1577, artist: 'GIMS', title: 'J\'me tire', genre: 'POP', votes: 0 },
    { id: 1578, artist: 'Glass Animals', title: 'Heat Waves', genre: 'POP', votes: 0 },
    { id: 1579, artist: 'Glitter Dream, Diana V, & Alex Parker', title: 'Alibi', genre: 'POP', votes: 0 },
    { id: 1580, artist: 'Gorillaz & De La Soul', title: 'Feel Good Inc.', genre: 'POP', votes: 0 },
    { id: 1581, artist: 'Gotye', title: 'Somebody That I Used To Know (feat. Kimbra)', genre: 'POP', votes: 0 },
    { id: 1582, artist: 'Gracie Abrams', title: 'That’s So True', genre: 'POP', votes: 0 },
    { id: 1583, artist: 'Guru Josh Project', title: 'Infinity 2008 (Klaas Vocal Edit)', genre: 'POP', votes: 0 },
    { id: 1584, artist: 'Gym Class Heroes', title: 'Stereo Hearts (feat. Adam Levine)', genre: 'POP', votes: 0 },
    { id: 1585, artist: 'Haddaway', title: 'What Is Love (7 Mix)', genre: 'POP', votes: 0 },
    { id: 1586, artist: 'Halsey', title: 'Without Me', genre: 'POP', votes: 0 },
    { id: 1587, artist: 'Harry Styles', title: 'As It Was', genre: 'POP', votes: 0 },
    { id: 1588, artist: 'Harry Styles', title: 'Sign of the Times', genre: 'POP', votes: 0 },
    { id: 1589, artist: 'Henry Moodie', title: 'drunk text', genre: 'POP', votes: 0 },
    { id: 1590, artist: 'Imagine Dragons', title: 'Believer', genre: 'POP', votes: 0 },
    { id: 1591, artist: 'Imagine Dragons', title: 'Thunder', genre: 'POP', votes: 0 },
    { id: 1592, artist: 'INNA', title: 'Amazing', genre: 'POP', votes: 0 },
    { id: 1593, artist: 'INNA', title: 'Deja Vu [Play & Win Radio Edit] (feat. Bob Taylor)', genre: 'POP', votes: 0 },
    { id: 1594, artist: 'INNA', title: 'Hot (Play & Win Radio Version)', genre: 'POP', votes: 0 },
    { id: 1595, artist: 'INNA', title: 'Sun is up', genre: 'POP', votes: 0 },
    { id: 1596, artist: 'Iyaz', title: 'Replay', genre: 'POP', votes: 0 },
    { id: 1597, artist: 'Jack Harlow', title: 'Lovin On Me', genre: 'POP', votes: 0 },
    { id: 1598, artist: 'James Arthur', title: 'Say You Won\'t Let Go', genre: 'POP', votes: 0 },
    { id: 1599, artist: 'James Blunt', title: 'You\'re Beautiful', genre: 'POP', votes: 0 },
    { id: 1600, artist: 'Jason Derulo', title: 'Talk Dirty (feat. 2 Chainz)', genre: 'POP', votes: 0 },
    { id: 1601, artist: 'Jason Derulo', title: 'Whatcha Say', genre: 'POP', votes: 0 },
    { id: 1602, artist: 'Jay Sean', title: 'Do You Remember (feat. Sean Paul & Lil Jon)', genre: 'POP', votes: 0 },
    { id: 1603, artist: 'Jay Sean', title: 'Down (feat. Lil Wayne)', genre: 'POP', votes: 0 },
    { id: 1604, artist: 'JAY-Z', title: 'Empire State Of Mind (feat. Alicia Keys)', genre: 'POP', votes: 0 },
    { id: 1605, artist: 'JAY-Z', title: 'Run This Town (feat. Rihanna & Kanye West)', genre: 'POP', votes: 0 },
    { id: 1606, artist: 'JENNIE & Doechii', title: 'ExtraL', genre: 'POP', votes: 0 },
    { id: 1607, artist: 'JENNIE & Dua Lipa', title: 'Handlebars', genre: 'POP', votes: 0 },
    { id: 1608, artist: 'Jennifer Lopez & Pitbull', title: 'On The Floor (Radio Edit)', genre: 'POP', votes: 0 },
    { id: 1609, artist: 'Jessie J', title: 'Domino', genre: 'POP', votes: 0 },
    { id: 1610, artist: 'Jessie J', title: 'Price Tag (feat. B.o.B)', genre: 'POP', votes: 0 },
    { id: 1611, artist: 'JISOO & ZAYN', title: 'EYES CLOSED', genre: 'POP', votes: 0 },
    { id: 1612, artist: 'John Legend', title: 'All of Me', genre: 'POP', votes: 0 },
    { id: 1613, artist: 'Juice WRLD', title: 'Lucid Dreams', genre: 'POP', votes: 0 },
    { id: 1614, artist: 'Jung Kook', title: 'Seven - Explicit Ver. (feat. Latto)', genre: 'POP', votes: 0 },
    { id: 1615, artist: 'Justin Bieber', title: 'Baby (feat. Ludacris)', genre: 'POP', votes: 0 },
    { id: 1616, artist: 'Justin Bieber', title: 'Beauty and a Beat (feat. Nicki Minaj)', genre: 'POP', votes: 0 },
    { id: 1617, artist: 'Justin Bieber', title: 'DAISIES', genre: 'POP', votes: 0 },
    { id: 1618, artist: 'Justin Bieber', title: 'Intentions (feat. Quavo)', genre: 'POP', votes: 0 },
    { id: 1619, artist: 'Justin Bieber', title: 'Never Say Never (feat. Jaden)', genre: 'POP', votes: 0 },
    { id: 1620, artist: 'Justin Bieber', title: 'Sorry', genre: 'POP', votes: 0 },
    { id: 1621, artist: 'Justin Bieber', title: 'What Do You Mean_', genre: 'POP', votes: 0 },
    { id: 1622, artist: 'Justin Bieber', title: 'YUKON', genre: 'POP', votes: 0 },
    { id: 1623, artist: 'Justin Timberlake', title: 'CAN\'T STOP THE FEELING! (from DreamWorks Animation\'s TROLLS)', genre: 'POP', votes: 0 },
    { id: 1624, artist: 'Justin Timberlake', title: 'Mirrors', genre: 'POP', votes: 0 },
    { id: 1625, artist: 'Justin Timberlake', title: 'SexyBack (feat. Timbaland)', genre: 'POP', votes: 0 },
    { id: 1626, artist: 'JVKE', title: 'her', genre: 'POP', votes: 0 },
    { id: 1627, artist: 'K\'NAAN', title: 'Wavin\'  Flag (Coca-Cola Celebration Mix)', genre: 'POP', votes: 0 },
    { id: 1628, artist: 'Kanye West', title: 'Flashing Lights (feat. Dwele)', genre: 'POP', votes: 0 },
    { id: 1629, artist: 'Katy Perry', title: 'California Gurls (feat. Snoop Dogg)', genre: 'POP', votes: 0 },
    { id: 1630, artist: 'Katy Perry', title: 'Dark Horse (feat. Juicy J)', genre: 'POP', votes: 0 },
    { id: 1631, artist: 'Katy Perry', title: 'Firework (Lyrics)', genre: 'POP', votes: 0 },
    { id: 1632, artist: 'Katy Perry', title: 'Hot N Cold', genre: 'POP', votes: 0 },
    { id: 1633, artist: 'Katy Perry', title: 'I Kissed A Girl', genre: 'POP', votes: 0 },
    { id: 1634, artist: 'Katy Perry', title: 'Last Friday Night (T.G.I.F.)', genre: 'POP', votes: 0 },
    { id: 1635, artist: 'Katy Perry', title: 'Roar', genre: 'POP', votes: 0 },
    { id: 1636, artist: 'Katy Perry', title: 'Teenage Dream', genre: 'POP', votes: 0 },
    { id: 1637, artist: 'Katy Perry', title: 'The One That Got Away', genre: 'POP', votes: 0 },
    { id: 1638, artist: 'Ke$ha', title: 'Die Young', genre: 'POP', votes: 0 },
    { id: 1639, artist: 'Ke$ha', title: 'TiK ToK', genre: 'POP', votes: 0 },
    { id: 1640, artist: 'Keane', title: 'Somewhere Only We Know', genre: 'POP', votes: 0 },
    { id: 1641, artist: 'Kendrick Lamar & SZA', title: 'All the Stars', genre: 'POP', votes: 0 },
    { id: 1642, artist: 'Kendrick Lamar & SZA', title: 'luther', genre: 'POP', votes: 0 },
    { id: 1643, artist: 'Kendrick Lamar', title: 'Not Like Us', genre: 'POP', votes: 0 },
    { id: 1644, artist: 'Kendrick Lamar', title: 'squabble up', genre: 'POP', votes: 0 },
    { id: 1645, artist: 'Kylie Minogue', title: 'Can\'t Get You out of My Head', genre: 'POP', votes: 0 },
    { id: 1646, artist: 'Lady Gaga & Bruno Mars', title: 'Die With A Smile', genre: 'POP', votes: 0 },
    { id: 1647, artist: 'Lady Gaga', title: 'Abracadabra', genre: 'POP', votes: 0 },
    { id: 1648, artist: 'Lady Gaga', title: 'Alejandro', genre: 'POP', votes: 0 },
    { id: 1649, artist: 'Lady Gaga', title: 'Always Remember Us This Way', genre: 'POP', votes: 0 },
    { id: 1650, artist: 'Lady Gaga', title: 'Bad Romance', genre: 'POP', votes: 0 },
    { id: 1651, artist: 'Lady Gaga', title: 'Just Dance (feat. Colby O\'Donis)', genre: 'POP', votes: 0 },
    { id: 1652, artist: 'Lady Gaga', title: 'Paparazzi', genre: 'POP', votes: 0 },
    { id: 1653, artist: 'Lady Gaga', title: 'Poker Face', genre: 'POP', votes: 0 },
    { id: 1654, artist: 'Lady Gaga', title: 'Telephone (feat. Beyoncé)', genre: 'POP', votes: 0 },
    { id: 1655, artist: 'Lady Gaga', title: 'The Dead Dance', genre: 'POP', votes: 0 },
    { id: 1656, artist: 'Lana Del Rey', title: 'Summertime Sadness', genre: 'POP', votes: 0 },
    { id: 1657, artist: 'Lana Del Rey', title: 'Young And Beautiful', genre: 'POP', votes: 0 },
    { id: 1658, artist: 'Laurent Wolf', title: 'No Stress (feat. Eric Carter)', genre: 'POP', votes: 0 },
    { id: 1659, artist: 'Lauv', title: 'I Like Me Better', genre: 'POP', votes: 0 },
    { id: 1660, artist: 'Lewis Capaldi', title: 'Someone You Loved', genre: 'POP', votes: 0 },
    { id: 1661, artist: 'Libianca', title: 'People', genre: 'POP', votes: 0 },
    { id: 1662, artist: 'Lil Nas X', title: 'Old Town Road (Remix) (feat. Billy Ray Cyrus)', genre: 'POP', votes: 0 },
    { id: 1663, artist: 'Lil Wayne', title: 'Lollipop (feat. Static Major)', genre: 'POP', votes: 0 },
    { id: 1664, artist: 'Linkin Park', title: 'In the End', genre: 'POP', votes: 0 },
    { id: 1665, artist: 'Linkin Park', title: 'Numb', genre: 'POP', votes: 0 },
    { id: 1666, artist: 'LISA', title: 'Born Again (feat. Doja Cat & RAYE)', genre: 'POP', votes: 0 },
    { id: 1667, artist: 'LISA', title: 'New Woman (feat. ROSALÍA)', genre: 'POP', votes: 0 },
    { id: 1668, artist: 'LMFAO', title: 'Party Rock Anthem (feat. Lauren Bennett & GoonRock)', genre: 'POP', votes: 0 },
    { id: 1669, artist: 'Lola Young', title: 'Messy', genre: 'POP', votes: 0 },
    { id: 1670, artist: 'Loona', title: 'Vamos a la Playa', genre: 'POP', votes: 0 },
    { id: 1671, artist: 'Loreen', title: 'Tattoo', genre: 'POP', votes: 0 },
    { id: 1672, artist: 'Lucenzo & Kenza Farah', title: 'Obsesión', genre: 'POP', votes: 0 },
    { id: 1673, artist: 'Lucenzo', title: 'Danza Kuduro (Version MTO) (feat. Don Omar)', genre: 'POP', votes: 0 },
    { id: 1674, artist: 'Lucenzo', title: 'Vem Dancar Kuduro (feat. Lucenzo)', genre: 'POP', votes: 0 },
    { id: 1675, artist: 'Luis Fonsi & Daddy Yankee', title: 'Despacito', genre: 'POP', votes: 0 },
    { id: 1676, artist: 'Lukas Graham', title: '7 Years', genre: 'POP', votes: 0 },
    { id: 1677, artist: 'M83', title: 'Midnight City', genre: 'POP', votes: 0 },
    { id: 1678, artist: 'Macklemore & Ryan Lewis', title: 'Can\'t Hold Us (feat. Ray Dalton)', genre: 'POP', votes: 0 },
    { id: 1679, artist: 'Madison Beer', title: 'make you mine', genre: 'POP', votes: 0 },
    { id: 1680, artist: 'MAGIC!', title: 'Rude', genre: 'POP', votes: 0 },
    { id: 1681, artist: 'Major Lazer', title: 'Lean On (feat. Major Lazer & DJ Snake)', genre: 'POP', votes: 0 },
    { id: 1682, artist: 'Man I Need', title: 'Olivia Dean (Lyrics)', genre: 'POP', votes: 0 },
    { id: 1683, artist: 'Mark Ronson', title: 'Uptown Funk (feat. Bruno Mars)', genre: 'POP', votes: 0 },
    { id: 1684, artist: 'Maroon 5', title: 'Girls Like You (Cardi B Version) (feat. Cardi B)', genre: 'POP', votes: 0 },
    { id: 1685, artist: 'Maroon 5', title: 'Moves like Jagger (Studio Recording from The Voice Performance) (feat. Christina Aguilera)', genre: 'POP', votes: 0 },
    { id: 1686, artist: 'Maroon 5', title: 'One More Night', genre: 'POP', votes: 0 },
    { id: 1687, artist: 'Maroon 5', title: 'Payphone (feat. Wiz Khalifa)', genre: 'POP', votes: 0 },
    { id: 1688, artist: 'Maroon 5', title: 'Sugar', genre: 'POP', votes: 0 },
    { id: 1689, artist: 'Martin Solveig & Dragonette', title: 'Hello', genre: 'POP', votes: 0 },
    { id: 1690, artist: 'Metro Boomin, The Weeknd & 21 Savage', title: 'Creepin\'', genre: 'POP', votes: 0 },
    { id: 1691, artist: 'Michael Jackson & Janet Jackson', title: 'Scream', genre: 'POP', votes: 0 },
    { id: 1692, artist: 'MIKA', title: 'Relax, Take It Easy', genre: 'POP', votes: 0 },
    { id: 1693, artist: 'Miley Cyrus', title: 'End of the World', genre: 'POP', votes: 0 },
    { id: 1694, artist: 'Miley Cyrus', title: 'Flowers', genre: 'POP', votes: 0 },
    { id: 1695, artist: 'Miley Cyrus', title: 'Party In The U.S.A.', genre: 'POP', votes: 0 },
    { id: 1696, artist: 'MIRA', title: 'Bad Booty', genre: 'POP', votes: 0 },
    { id: 1697, artist: 'Mira', title: 'Come With Me', genre: 'POP', votes: 0 },
    { id: 1698, artist: 'MIRA', title: 'Duro', genre: 'POP', votes: 0 },
    { id: 1699, artist: 'MIRA', title: 'Ladida', genre: 'POP', votes: 0 },
    { id: 1700, artist: 'MIRA', title: 'Love Again', genre: 'POP', votes: 0 },
    { id: 1701, artist: 'MIRA', title: 'Ring Ring', genre: 'POP', votes: 0 },
    { id: 1702, artist: 'Mohombi', title: 'Bumpy Ride (feat. Pitbull)', genre: 'POP', votes: 0 },
    { id: 1703, artist: 'Myles Smith', title: 'Stargazing', genre: 'POP', votes: 0 },
    { id: 1704, artist: 'Natasha Bedingfield', title: 'Unwritten', genre: 'POP', votes: 0 },
    { id: 1705, artist: 'Nelly', title: 'Dilemma (feat. Kelly Rowland)', genre: 'POP', votes: 0 },
    { id: 1706, artist: 'Nelly', title: 'Just A Dream', genre: 'POP', votes: 0 },
    { id: 1707, artist: 'Nelly Furtado', title: 'Promiscuous (feat. Timbaland)', genre: 'POP', votes: 0 },
    { id: 1708, artist: 'Nelly Furtado', title: 'Say It Right', genre: 'POP', votes: 0 },
    { id: 1709, artist: 'Nicki Minaj', title: 'Starships', genre: 'POP', votes: 0 },
    { id: 1710, artist: 'Nico & Vinz', title: 'Am I Wrong', genre: 'POP', votes: 0 },
    { id: 1711, artist: 'Ofenbach', title: 'Overdrive (feat. Norma Jean Martine)', genre: 'POP', votes: 0 },
    { id: 1712, artist: 'Olivia Rodrigo', title: 'deja vu', genre: 'POP', votes: 0 },
    { id: 1713, artist: 'Olivia Rodrigo', title: 'vampire', genre: 'POP', votes: 0 },
    { id: 1714, artist: 'Olly Alexander (Years & Years)', title: 'King', genre: 'POP', votes: 0 },
    { id: 1715, artist: 'One Direction', title: 'Night Changes', genre: 'POP', votes: 0 },
    { id: 1716, artist: 'OneRepublic', title: 'Counting Stars', genre: 'POP', votes: 0 },
    { id: 1717, artist: 'Owl City', title: 'Fireflies', genre: 'POP', votes: 0 },
    { id: 1718, artist: 'P!NK', title: 'Just Give Me a Reason (feat. Nate Ruess)', genre: 'POP', votes: 0 },
    { id: 1719, artist: 'Passenger', title: 'Let Her Go', genre: 'POP', votes: 0 },
    { id: 1720, artist: 'Pharrell Williams', title: 'Happy (From Despicable Me 2)', genre: 'POP', votes: 0 },
    { id: 1721, artist: 'Pitbull & Kesha', title: 'Timber', genre: 'POP', votes: 0 },
    { id: 1722, artist: 'Pitbull', title: 'Hey Baby (Drop It to the Floor) [Radio Edit] (feat. T-Pain)', genre: 'POP', votes: 0 },
    { id: 1723, artist: 'Pitbull', title: 'Hotel Room Service', genre: 'POP', votes: 0 },
    { id: 1724, artist: 'Pitbull', title: 'International Love (feat. Chris Brown)', genre: 'POP', votes: 0 },
    { id: 1725, artist: 'Pitbull', title: 'Rain Over Me (feat. Marc Anthony)', genre: 'POP', votes: 0 },
    { id: 1726, artist: 'Pitbull, Afrojack & Ne-Yo', title: 'Give Me Everything (feat. Nayer)', genre: 'POP', votes: 0 },
    { id: 1727, artist: 'Playboi Carti & Skepta', title: 'TOXIC', genre: 'POP', votes: 0 },
    { id: 1728, artist: 'Post Malone', title: 'I Had Some Help (feat. Morgan Wallen)', genre: 'POP', votes: 0 },
    { id: 1729, artist: 'PSY', title: 'Gangnam Style', genre: 'POP', votes: 0 },
    { id: 1730, artist: 'Pynk Beard', title: 'Mine, Lord Willing', genre: 'POP', votes: 0 },
    { id: 1731, artist: 'Rag\'n\'Bone Man', title: 'Human', genre: 'POP', votes: 0 },
    { id: 1732, artist: 'RAYE & 070 Shake', title: 'Escapism.', genre: 'POP', votes: 0 },
    { id: 1733, artist: 'RAYE', title: 'WHERE IS MY HUSBAND!', genre: 'POP', votes: 0 },
    { id: 1734, artist: 'RAZZ & Joel Winterflood', title: 'Home', genre: 'POP', votes: 0 },
    { id: 1735, artist: 'Rema & Selena Gomez', title: 'Calm Down', genre: 'POP', votes: 0 },
    { id: 1736, artist: 'Rihanna & Calvin Harris', title: 'We Found Love', genre: 'POP', votes: 0 },
    { id: 1737, artist: 'Rihanna', title: 'Breakin\' Dishes', genre: 'POP', votes: 0 },
    { id: 1738, artist: 'Rihanna', title: 'Diamonds', genre: 'POP', votes: 0 },
    { id: 1739, artist: 'Rihanna', title: 'Disturbia', genre: 'POP', votes: 0 },
    { id: 1740, artist: 'Rihanna', title: 'Don\'t Stop The Music', genre: 'POP', votes: 0 },
    { id: 1741, artist: 'Rihanna', title: 'Love On The Brain', genre: 'POP', votes: 0 },
    { id: 1742, artist: 'Rihanna', title: 'Man Down', genre: 'POP', votes: 0 },
    { id: 1743, artist: 'Rihanna', title: 'Only Girl (In The World)', genre: 'POP', votes: 0 },
    { id: 1744, artist: 'Rihanna', title: 'Pon de Replay', genre: 'POP', votes: 0 },
    { id: 1745, artist: 'Rihanna', title: 'Rude Boy', genre: 'POP', votes: 0 },
    { id: 1746, artist: 'Rihanna', title: 'SOS', genre: 'POP', votes: 0 },
    { id: 1747, artist: 'Rihanna', title: 'Stay (feat. Mikky Ekko)', genre: 'POP', votes: 0 },
    { id: 1748, artist: 'Rihanna', title: 'Take A Bow', genre: 'POP', votes: 0 },
    { id: 1749, artist: 'Rihanna', title: 'Umbrella (Radio Edit) (feat. JAY-Z)', genre: 'POP', votes: 0 },
    { id: 1750, artist: 'Rihanna', title: 'What\'s My Name_ (feat. Drake)', genre: 'POP', votes: 0 },
    { id: 1751, artist: 'Rihanna', title: 'Where Have You Been', genre: 'POP', votes: 0 },
    { id: 1752, artist: 'Robert Miles', title: 'Children', genre: 'POP', votes: 0 },
    { id: 1753, artist: 'Robin Thicke', title: 'Blurred Lines (feat. T.I. & Pharrell)', genre: 'POP', votes: 0 },
    { id: 1754, artist: 'ROSÉ & Bruno Mars', title: 'APT.', genre: 'POP', votes: 0 },
    { id: 1755, artist: 'ROSÉ', title: 'number one girl', genre: 'POP', votes: 0 },
    { id: 1756, artist: 'ROSÉ', title: 'toxic till the end', genre: 'POP', votes: 0 },
    { id: 1757, artist: 'Sabrina Carpenter', title: 'Espresso', genre: 'POP', votes: 0 },
    { id: 1758, artist: 'Sabrina Carpenter', title: 'Feather', genre: 'POP', votes: 0 },
    { id: 1759, artist: 'Sabrina Carpenter', title: 'Manchild', genre: 'POP', votes: 0 },
    { id: 1760, artist: 'Sabrina Carpenter', title: 'Please Please Please', genre: 'POP', votes: 0 },
    { id: 1761, artist: 'Sabrina Carpenter', title: 'Tears', genre: 'POP', votes: 0 },
    { id: 1762, artist: 'Sabrina Carpenter', title: 'When Did You Get Hot_', genre: 'POP', votes: 0 },
    { id: 1763, artist: 'Sam Smith', title: 'I\'m Not The Only One', genre: 'POP', votes: 0 },
    { id: 1764, artist: 'Sean Kingston & Justin Bieber', title: 'Eenie Meenie', genre: 'POP', votes: 0 },
    { id: 1765, artist: 'Sean Kingston', title: 'Beautiful Girls', genre: 'POP', votes: 0 },
    { id: 1766, artist: 'Sean Paul', title: 'Got 2 Luv U (feat. Alexis Jordan)', genre: 'POP', votes: 0 },
    { id: 1767, artist: 'Sean Paul', title: 'Hold My Hand (feat. Zaho)', genre: 'POP', votes: 0 },
    { id: 1768, artist: 'Sean Paul', title: 'I\'m Still in Love with You (feat. Sasha)', genre: 'POP', votes: 0 },
    { id: 1769, artist: 'Sean Paul', title: 'Temperature', genre: 'POP', votes: 0 },
    { id: 1770, artist: 'Sevdaliza, Pabllo Vittar & Yseult', title: 'Alibi (with Pabllo Vittar & Yseult)', genre: 'POP', votes: 0 },
    { id: 1771, artist: 'Sexion d\'Assaut', title: 'Désolé', genre: 'POP', votes: 0 },
    { id: 1772, artist: 'Shaboozey', title: 'A Bar Song (Tipsy)', genre: 'POP', votes: 0 },
    { id: 1773, artist: 'Shaggy & Limitlezz', title: 'Boombastic', genre: 'POP', votes: 0 },
    { id: 1774, artist: 'Shakira', title: 'Addicted to You', genre: 'POP', votes: 0 },
    { id: 1775, artist: 'Shakira', title: 'Hips Don\'t Lie (feat. Wyclef Jean)', genre: 'POP', votes: 0 },
    { id: 1776, artist: 'Shakira', title: 'Waka Waka (This Time for Africa) [The Official 2010 FIFA World Cup (TM) Song] (feat. Freshlyground)', genre: 'POP', votes: 0 },
    { id: 1777, artist: 'Shakira', title: 'Whenever, Wherever', genre: 'POP', votes: 0 },
    { id: 1778, artist: 'Shawn Mendes & Camila Cabello', title: 'Señorita', genre: 'POP', votes: 0 },
    { id: 1779, artist: 'Shawn Mendes', title: 'There\'s Nothing Holdin\' Me Back', genre: 'POP', votes: 0 },
    { id: 1780, artist: 'Shawn Mendes', title: 'Treat You Better', genre: 'POP', votes: 0 },
    { id: 1781, artist: 'Sia', title: 'Chandelier', genre: 'POP', votes: 0 },
    { id: 1782, artist: 'Sia', title: 'Cheap Thrills', genre: 'POP', votes: 0 },
    { id: 1783, artist: 'Unknown Artist', title: 'Soda Pop Official Lyric Video _ KPop Demon Hunters _ Sony Animation', genre: 'POP', votes: 0 },
    { id: 1784, artist: 'sombr', title: 'back to friends', genre: 'POP', votes: 0 },
    { id: 1785, artist: 'Sophie Ellis-Bextor', title: 'Murder On The Dancefloor', genre: 'POP', votes: 0 },
    { id: 1786, artist: 'Stephen Sanchez', title: 'Until I Found You', genre: 'POP', votes: 0 },
    { id: 1787, artist: 'Swedish House Mafia', title: 'Don\'t You Worry Child (Radio Edit) (feat. John Martin)', genre: 'POP', votes: 0 },
    { id: 1788, artist: 'SZA', title: 'Kill Bill', genre: 'POP', votes: 0 },
    { id: 1789, artist: 'SZA', title: 'Snooze', genre: 'POP', votes: 0 },
    { id: 1790, artist: 'Taio Cruz', title: 'Break Your Heart (feat. Ludacris)', genre: 'POP', votes: 0 },
    { id: 1791, artist: 'Taio Cruz', title: 'Dynamite', genre: 'POP', votes: 0 },
    { id: 1792, artist: 'Taio Cruz', title: 'Hangover (feat. Flo Rida)', genre: 'POP', votes: 0 },
    { id: 1793, artist: 'Tate McRae', title: 'greedy', genre: 'POP', votes: 0 },
    { id: 1794, artist: 'Tate McRae', title: 'It\'s ok I\'m ok', genre: 'POP', votes: 0 },
    { id: 1795, artist: 'Tate McRae', title: 'Just Keep Watching (From F1 The Movie)', genre: 'POP', votes: 0 },
    { id: 1796, artist: 'Tate McRae', title: 'Revolving door', genre: 'POP', votes: 0 },
    { id: 1797, artist: 'Tate McRae', title: 'Sports car', genre: 'POP', votes: 0 },
    { id: 1798, artist: 'Taylor Swift', title: 'Blank Space', genre: 'POP', votes: 0 },
    { id: 1799, artist: 'Taylor Swift', title: 'Fortnight (feat. Post Malone)', genre: 'POP', votes: 0 },
    { id: 1800, artist: 'Taylor Swift', title: 'Opalite', genre: 'POP', votes: 0 },
    { id: 1801, artist: 'Taylor Swift', title: 'Shake It Off', genre: 'POP', votes: 0 },
    { id: 1802, artist: 'Taylor Swift', title: 'The Fate of Ophelia', genre: 'POP', votes: 0 },
    { id: 1803, artist: 'Teddy Swims', title: 'Bad Dreams', genre: 'POP', votes: 0 },
    { id: 1804, artist: 'Teddy Swims', title: 'The Door', genre: 'POP', votes: 0 },
    { id: 1805, artist: 'The Black Eyed Peas', title: 'Boom Boom Pow', genre: 'POP', votes: 0 },
    { id: 1806, artist: 'The Black Eyed Peas', title: 'I Gotta Feeling', genre: 'POP', votes: 0 },
    { id: 1807, artist: 'The Black Eyed Peas', title: 'Imma Be', genre: 'POP', votes: 0 },
    { id: 1808, artist: 'The Black Eyed Peas', title: 'Just Can’t Get Enough', genre: 'POP', votes: 0 },
    { id: 1809, artist: 'The Black Eyed Peas', title: 'Meet Me Halfway', genre: 'POP', votes: 0 },
    { id: 1810, artist: 'The Black Eyed Peas', title: 'My Humps (Single Version)', genre: 'POP', votes: 0 },
    { id: 1811, artist: 'The Black Eyed Peas', title: 'Rock That Body', genre: 'POP', votes: 0 },
    { id: 1812, artist: 'The Black Eyed Peas', title: 'The Time (Dirty Bit)', genre: 'POP', votes: 0 },
    { id: 1813, artist: 'The Black Eyed Peas', title: 'Where Is the Love_', genre: 'POP', votes: 0 },
    { id: 1814, artist: 'The Chainsmokers & Coldplay', title: 'Something Just Like This', genre: 'POP', votes: 0 },
    { id: 1815, artist: 'The Chainsmokers', title: 'Closer (feat. Halsey)', genre: 'POP', votes: 0 },
    { id: 1816, artist: 'The Chainsmokers', title: 'Don\'t Let Me Down (feat. Daya)', genre: 'POP', votes: 0 },
    { id: 1817, artist: 'The Kid LAROI & Justin Bieber', title: 'STAY', genre: 'POP', votes: 0 },
    { id: 1818, artist: 'The Neighbourhood', title: 'Sweater Weather', genre: 'POP', votes: 0 },
    { id: 1819, artist: 'The Pussycat Dolls', title: 'Buttons (Final Edit Version) (feat. Snoop Dogg)', genre: 'POP', votes: 0 },
    { id: 1820, artist: 'The Weeknd & Anitta', title: 'São Paulo', genre: 'POP', votes: 0 },
    { id: 1821, artist: 'The Weeknd & Ariana Grande', title: 'Die For You (Remix)', genre: 'POP', votes: 0 },
    { id: 1822, artist: 'The Weeknd', title: 'Blinding Lights', genre: 'POP', votes: 0 },
    { id: 1823, artist: 'The Weeknd', title: 'Cry For Me', genre: 'POP', votes: 0 },
    { id: 1824, artist: 'The Weeknd', title: 'I Feel It Coming (feat. Daft Punk)', genre: 'POP', votes: 0 },
    { id: 1825, artist: 'The Weeknd', title: 'Save Your Tears', genre: 'POP', votes: 0 },
    { id: 1826, artist: 'The Weeknd', title: 'Starboy (feat. Daft Punk)', genre: 'POP', votes: 0 },
    { id: 1827, artist: 'The Weeknd', title: 'The Hills', genre: 'POP', votes: 0 },
    { id: 1828, artist: 'Timbaland', title: 'Apologize (feat. OneRepublic)', genre: 'POP', votes: 0 },
    { id: 1829, artist: 'Timbaland', title: 'The Way I Are (feat. Keri Hilson & D.O.E.)', genre: 'POP', votes: 0 },
    { id: 1830, artist: 'TOESUP & Che Ree', title: 'Ice Cream', genre: 'POP', votes: 0 },
    { id: 1831, artist: 'TOESUP & Smiley', title: 'Two Feet', genre: 'POP', votes: 0 },
    { id: 1832, artist: 'Tom Odell', title: 'Another Love', genre: 'POP', votes: 0 },
    { id: 1833, artist: 'Tommy Richman', title: 'MILLION DOLLAR BABY', genre: 'POP', votes: 0 },
    { id: 1834, artist: 'Train', title: 'Drive By', genre: 'POP', votes: 0 },
    { id: 1835, artist: 'Train', title: 'Hey, Soul Sister', genre: 'POP', votes: 0 },
    { id: 1836, artist: 'twenty one pilots', title: 'Heathens', genre: 'POP', votes: 0 },
    { id: 1837, artist: 'twenty one pilots', title: 'Stressed Out', genre: 'POP', votes: 0 },
    { id: 1838, artist: 'Tyga', title: 'Taste (feat. Offset)', genre: 'POP', votes: 0 },
    { id: 1839, artist: 'Tyla', title: 'Water', genre: 'POP', votes: 0 },
    { id: 1840, artist: 'Usher', title: 'DJ Got Us Fallin\' In Love (feat. Pitbull)', genre: 'POP', votes: 0 },
    { id: 1841, artist: 'Usher', title: 'More (RedOne Jimmy Joker Remix)', genre: 'POP', votes: 0 },
    { id: 1842, artist: 'Usher', title: 'Yeah! (feat. Lil Jon & Ludacris)', genre: 'POP', votes: 0 },
    { id: 1843, artist: 'Vance Joy', title: 'Riptide', genre: 'POP', votes: 0 },
    { id: 1844, artist: 'Wiz Khalifa & Snoop Dogg', title: 'Young, Wild & Free (feat. Bruno Mars)', genre: 'POP', votes: 0 },
    { id: 1845, artist: 'Wiz Khalifa', title: 'Black and Yellow', genre: 'POP', votes: 0 },
    { id: 1846, artist: 'Wiz Khalifa', title: 'See You Again (feat. Charlie Puth)', genre: 'POP', votes: 0 },
    { id: 1847, artist: 'Young Money', title: 'BedRock (feat. Lloyd)', genre: 'POP', votes: 0 },
    { id: 1848, artist: 'yung kai', title: 'blue', genre: 'POP', votes: 0 },
    { id: 1849, artist: 'Zac Efron & Zendaya', title: 'Rewrite The Stars', genre: 'POP', votes: 0 },
    { id: 1850, artist: 'ZAYN', title: 'Dusk Till Dawn (Radio Edit) (feat. Sia)', genre: 'POP', votes: 0 },
    { id: 1851, artist: 'Тимати', title: 'Welcome to St. Tropez [DJ Antoine vs. Mad Mark Remix] (feat. Kalenna)', genre: 'POP', votes: 0 },
    { id: 1852, artist: '정국 (Jung Kook)', title: 'Standing Next to You', genre: 'POP', votes: 0 },
    { id: 1853, artist: 'Alan Walker', title: 'Me, Myself and The Night', genre: 'EDM', votes: 0 },
    { id: 1854, artist: 'Alesso & Becky Hill', title: 'Surrender', genre: 'EDM', votes: 0 },
    { id: 1855, artist: 'Alle Farben', title: 'Call My Name (feat. Sofiloud)', genre: 'EDM', votes: 0 },
    { id: 1856, artist: 'Alle Farben', title: 'Let It Rain Down (feat. PollyAnna)', genre: 'EDM', votes: 0 },
    { id: 1857, artist: 'Alle Farben, Graham Candy & Lahos', title: 'Flowers', genre: 'EDM', votes: 0 },
    { id: 1858, artist: 'Alok & Ely Oaks', title: 'Tsunami', genre: 'EDM', votes: 0 },
    { id: 1859, artist: 'Alok, Mondello\'G, CERES & Tribbs', title: 'LET\'S GET FKD UP', genre: 'EDM', votes: 0 },
    { id: 1860, artist: 'Alok, Sigala & Ellie Goulding', title: 'All By Myself', genre: 'EDM', votes: 0 },
    { id: 1861, artist: 'ALTÉGO', title: 'Now That I\'m Gone', genre: 'EDM', votes: 0 },
    { id: 1862, artist: 'Anyma & Ellie Goulding', title: 'Hypnotized', genre: 'EDM', votes: 0 },
    { id: 1863, artist: 'Anyma', title: 'Pictures Of You', genre: 'EDM', votes: 0 },
    { id: 1864, artist: 'ATB & Dopamine', title: 'Don\'t Stop (I Wanna Know)', genre: 'EDM', votes: 0 },
    { id: 1865, artist: 'Badger & Natasha Bedingfield', title: 'These Words', genre: 'EDM', votes: 0 },
    { id: 1866, artist: 'Ben Nicky, ARTY & Chicane', title: 'Oxygen', genre: 'EDM', votes: 0 },
    { id: 1867, artist: 'BENNETT', title: 'Mamma Mia [Techno Mix] (feat. Mentissa)', genre: 'EDM', votes: 0 },
    { id: 1868, artist: 'BENNETT', title: 'Vois sur ton chemin (Techno Mix)', genre: 'EDM', votes: 0 },
    { id: 1869, artist: 'BL3SS & CamrinWatsin', title: 'Kisses (feat. bbyclose)', genre: 'EDM', votes: 0 },
    { id: 1870, artist: 'BLACKPINK', title: 'JUMP', genre: 'EDM', votes: 0 },
    { id: 1871, artist: 'BLOND_ISH & Stevie Appleton', title: 'Never Walk Alone', genre: 'EDM', votes: 0 },
    { id: 1872, artist: 'Bodyshakers', title: 'Put Your Hands Up', genre: 'EDM', votes: 0 },
    { id: 1873, artist: 'Boris Way & Jaimes', title: 'I Will Wait', genre: 'EDM', votes: 0 },
    { id: 1874, artist: 'Britney Spears', title: 'I Wanna Go - John Summit Remix', genre: 'EDM', votes: 0 },
    { id: 1875, artist: 'Calvin Harris & Jessie Reyez', title: 'Ocean', genre: 'EDM', votes: 0 },
    { id: 1876, artist: 'Calvin Harris & Sam Smith', title: 'Desire', genre: 'EDM', votes: 0 },
    { id: 1877, artist: 'Calvin Harris', title: 'Blessings (feat. Clementine Douglas)', genre: 'EDM', votes: 0 },
    { id: 1878, artist: 'Cheat Codes & salem ilese', title: 'TYSM', genre: 'EDM', votes: 0 },
    { id: 1879, artist: 'Cheat Codes, Punctual & Raphaella', title: 'Find Love Now', genre: 'EDM', votes: 0 },
    { id: 1880, artist: 'CHRYSTAL', title: 'The Days (NOTION Remix)', genre: 'EDM', votes: 0 },
    { id: 1881, artist: 'Clean Bandit, Tiësto & Leony', title: 'Tell Me Where U Go (Tiësto VIP Mix)', genre: 'EDM', votes: 0 },
    { id: 1882, artist: 'Creeds', title: 'Push Up (Short Version)', genre: 'EDM', votes: 0 },
    { id: 1883, artist: 'Curbi & PollyAnna', title: 'Vertigo', genre: 'EDM', votes: 0 },
    { id: 1884, artist: 'CYRIL, MOONLGHT & The La\'s', title: 'There She Goes', genre: 'EDM', votes: 0 },
    { id: 1885, artist: 'David Guetta & Alesso', title: 'Never Going Home Tonight (feat. Madison Love)', genre: 'EDM', votes: 0 },
    { id: 1886, artist: 'David Guetta & Benny Benassi', title: 'Satisfaction', genre: 'EDM', votes: 0 },
    { id: 1887, artist: 'David Guetta & Sia', title: 'Beautiful People', genre: 'EDM', votes: 0 },
    { id: 1888, artist: 'David Guetta, Alphaville & Ava Max', title: 'Forever Young', genre: 'EDM', votes: 0 },
    { id: 1889, artist: 'David Guetta, Hypaton & Bonnie Tyler', title: 'Together', genre: 'EDM', votes: 0 },
    { id: 1890, artist: 'Dimitri Vegas & Like Mike, Tiësto, Dido & W&W', title: 'Thank You (Not So Bad)', genre: 'EDM', votes: 0 },
    { id: 1891, artist: 'Dimitri Vegas & Like Mike, W&W & Marnik', title: 'YEAH', genre: 'EDM', votes: 0 },
    { id: 1892, artist: 'Dimitri Vegas, Steve Aoki, Sound of Legend & Ann Lee', title: '2 Times', genre: 'EDM', votes: 0 },
    { id: 1893, artist: 'Dimitri Vegas, Vin & Zion', title: 'Don\'t Stop (The Music)', genre: 'EDM', votes: 0 },
    { id: 1894, artist: 'Disco Lines & Tinashe', title: 'No Broke Boys', genre: 'EDM', votes: 0 },
    { id: 1895, artist: 'DJ Kuba, Neitan, & Bounce Inc.', title: 'Blade', genre: 'EDM', votes: 0 },
    { id: 1896, artist: 'DJ Quasar & Eira Bergström', title: 'Autumn Skies', genre: 'EDM', votes: 0 },
    { id: 1897, artist: 'Dom Dolla', title: 'Dreamin (feat. Daya)', genre: 'EDM', votes: 0 },
    { id: 1898, artist: 'Don Diablo & Felix Jaehn', title: 'Monster', genre: 'EDM', votes: 0 },
    { id: 1899, artist: 'Eira Bergström', title: 'In My Dreams', genre: 'EDM', votes: 0 },
    { id: 1900, artist: 'Ely Oaks', title: 'Running Around', genre: 'EDM', votes: 0 },
    { id: 1901, artist: 'Emily Esthela & IMM PROJECT', title: 'Bitter', genre: 'EDM', votes: 0 },
    { id: 1902, artist: 'Ethan Nartim & Zouchy', title: 'Without You', genre: 'EDM', votes: 0 },
    { id: 1903, artist: 'Ethan Nartim', title: 'Running Up That Hill (A Deal With God) - Dance Version (Extended Speed Up)', genre: 'EDM', votes: 0 },
    { id: 1904, artist: 'Fcukers', title: 'I Like It Like That', genre: 'EDM', votes: 0 },
    { id: 1905, artist: 'Gabry Ponte & ONESOLO', title: 'Shining', genre: 'EDM', votes: 0 },
    { id: 1906, artist: 'Gabry Ponte', title: 'Exotica (feat. Greg Taro)', genre: 'EDM', votes: 0 },
    { id: 1907, artist: 'Galantis, David Guetta & 5 Seconds of Summer', title: 'Lighter', genre: 'EDM', votes: 0 },
    { id: 1908, artist: 'Gindo & Marie Fischer', title: 'Murder On The DanceFloor (Techno Festival Mix)', genre: 'EDM', votes: 0 },
    { id: 1909, artist: 'Gindo', title: 'Komodo', genre: 'EDM', votes: 0 },
    { id: 1910, artist: 'Gindo', title: 'Mamma Maria (Dance Mix)', genre: 'EDM', votes: 0 },
    { id: 1911, artist: 'Gotye, FISHER & Chris Lake', title: 'Somebody (feat. Kimbra & Sante Sansone)', genre: 'EDM', votes: 0 },
    { id: 1912, artist: 'IMM PROJECT & Marie Fischer', title: 'BOOM BOOM BOOM', genre: 'EDM', votes: 0 },
    { id: 1913, artist: 'IMM PROJECT & Marie Fischer', title: 'I ́m Alone', genre: 'EDM', votes: 0 },
    { id: 1914, artist: 'IMM PROJECT & Marie Fischer', title: 'No Matter', genre: 'EDM', votes: 0 },
    { id: 1915, artist: 'IMM PROJECT, Marie Fischer & Gindo', title: 'Rom Pe Lo', genre: 'EDM', votes: 0 },
    { id: 1916, artist: 'IMM PROJECT, Marie Fischer & TOCHIMON', title: 'When You Smile', genre: 'EDM', votes: 0 },
    { id: 1917, artist: 'IMM PROJECT, Marie Fischer, & Dorian Kai', title: 'Mamma Mia', genre: 'EDM', votes: 0 },
    { id: 1918, artist: 'Indila & BENNETT', title: 'Dernière danse (Techno Mix)', genre: 'EDM', votes: 0 },
    { id: 1919, artist: 'Jaden Bojsen, David Guetta & Sami Brielle', title: 'Let\'s Go', genre: 'EDM', votes: 0 },
    { id: 1920, artist: 'James Hype', title: 'Don\'t Wake Me Up', genre: 'EDM', votes: 0 },
    { id: 1921, artist: 'Jax Jones & Zoe Wees', title: 'Never Be Lonely', genre: 'EDM', votes: 0 },
    { id: 1922, artist: 'Jaxomy & Olly Alexander (Years & Years)', title: 'Desire', genre: 'EDM', votes: 0 },
    { id: 1923, artist: 'Joel Corry', title: 'Be Alright', genre: 'EDM', votes: 0 },
    { id: 1924, artist: 'John Summit & HAYLA', title: 'Shiver', genre: 'EDM', votes: 0 },
    { id: 1925, artist: 'John Summit', title: 'crystallized (feat. Inéz)', genre: 'EDM', votes: 0 },
    { id: 1926, artist: 'John Summit', title: 'light years (feat. Inéz)', genre: 'EDM', votes: 0 },
    { id: 1927, artist: 'John Summit, Sub Focus & Julia Church', title: 'Go Back', genre: 'EDM', votes: 0 },
    { id: 1928, artist: 'Jonas Blue & RANI', title: 'Finally', genre: 'EDM', votes: 0 },
    { id: 1929, artist: 'Jonas Blue, Sam Feldt, Endless Summer & Sadie Rose Van', title: 'Rest Of My Life', genre: 'EDM', votes: 0 },
    { id: 1930, artist: 'KAAZE', title: 'Destination Calabria', genre: 'EDM', votes: 0 },
    { id: 1931, artist: 'Kato Jimenez, Aitor Galan & Jia Miles', title: 'Freed From Desire', genre: 'EDM', votes: 0 },
    { id: 1932, artist: 'Kris Kross Amsterdam, Eyelar & EYLR', title: 'Mr. Lie to Me', genre: 'EDM', votes: 0 },
    { id: 1933, artist: 'LARETTO & Karla B', title: 'Contigo (Dance Mix - Extended)', genre: 'EDM', votes: 0 },
    { id: 1934, artist: 'Lost Frequencies & Bomfunk MC\'s', title: 'Freestyler (Rock The Microphone)', genre: 'EDM', votes: 0 },
    { id: 1935, artist: 'Lucas & Steve, LAWRENT & Izzy Bizu', title: 'Oh My Lord', genre: 'EDM', votes: 0 },
    { id: 1936, artist: 'Lucy Lush', title: 'Soltera (Dance Mix)', genre: 'EDM', votes: 0 },
    { id: 1937, artist: 'Malugi & Paige Tomlinson', title: 'Chiggy Chiggy (Paige Tomlinson Remix) (feat. Inéz)', genre: 'EDM', votes: 0 },
    { id: 1938, artist: 'Marie Fischer', title: 'I Need Your Love', genre: 'EDM', votes: 0 },
    { id: 1939, artist: 'Marnik, Naeleck & VINAI', title: 'Boyz In Paris', genre: 'EDM', votes: 0 },
    { id: 1940, artist: 'Marshmello, Ellie Goulding & AVAION', title: 'Save My Love', genre: 'EDM', votes: 0 },
    { id: 1941, artist: 'Martin Garrix & Jex', title: 'Told You So', genre: 'EDM', votes: 0 },
    { id: 1942, artist: 'Martin Garrix & Sem Vox', title: 'Gravity (feat. Jaimes)', genre: 'EDM', votes: 0 },
    { id: 1943, artist: 'Martin Garrix', title: 'Smile (feat. Carolina Liar)', genre: 'EDM', votes: 0 },
    { id: 1944, artist: 'Massano, TH;EN & Carlo Whale', title: 'Touch Me', genre: 'EDM', votes: 0 },
    { id: 1945, artist: 'Matt Sassari & SIDEPIECE', title: 'Elektro', genre: 'EDM', votes: 0 },
    { id: 1946, artist: 'Matt Sassari, Hugel & Sonique', title: 'It Feels So Good', genre: 'EDM', votes: 0 },
    { id: 1947, artist: 'Matway & June', title: 'Walking Away (Infinity)', genre: 'EDM', votes: 0 },
    { id: 1948, artist: 'Mondello\'G, 3rd Wall & CERES', title: 'Delirious (French Version)', genre: 'EDM', votes: 0 },
    { id: 1949, artist: 'Morgan Seatree & Florence + The Machine', title: 'Say My Name (Remix)', genre: 'EDM', votes: 0 },
    { id: 1950, artist: 'MORTEN & David Guetta', title: 'Lucky', genre: 'EDM', votes: 0 },
    { id: 1951, artist: 'Nathan Dawe, Joel Corry & SACHA', title: 'HIGHER', genre: 'EDM', votes: 0 },
    { id: 1952, artist: 'Nifra', title: 'Time (feat. Sarah de Warren)', genre: 'EDM', votes: 0 },
    { id: 1953, artist: 'Ofenbach', title: 'Need You The Most', genre: 'EDM', votes: 0 },
    { id: 1954, artist: 'Oliver Heldens & Julia Church', title: 'Ruins', genre: 'EDM', votes: 0 },
    { id: 1955, artist: 'PAWSA & Adventures Of Stevie V', title: 'Dirty Cash (Money Talks)', genre: 'EDM', votes: 0 },
    { id: 1956, artist: 'Perfect Pitch & Rocco', title: 'Sweet Dreams', genre: 'EDM', votes: 0 },
    { id: 1957, artist: 'R3HAB, INNA & Sash!', title: 'Rock My Body', genre: 'EDM', votes: 0 },
    { id: 1958, artist: 'R3HAB, Mufasa & Hypeman & RANI', title: 'Believe (Shooting Stars)', genre: 'EDM', votes: 0 },
    { id: 1959, artist: 'Robin Schulz & CYRIL', title: 'World Gone Wild (feat. Sam Martin)', genre: 'EDM', votes: 0 },
    { id: 1960, artist: 'Robin Schulz, Timmy Trumpet & KOPPY', title: 'All the Things She Said', genre: 'EDM', votes: 0 },
    { id: 1961, artist: 'Sam Feldt', title: 'Heart Like Mine (feat. Rosa Linn)', genre: 'EDM', votes: 0 },
    { id: 1962, artist: 'Sam Feldt, Jonas Blue, Endless Summer, and Violet Days', title: 'Crying On The Dancefloor', genre: 'EDM', votes: 0 },
    { id: 1963, artist: 'Scooter & Giuseppe Ottaviani', title: 'Hyper Hyper', genre: 'EDM', votes: 0 },
    { id: 1964, artist: 'Sonny Fodera, Jazzy & D.O.D', title: 'Somedays', genre: 'EDM', votes: 0 },
    { id: 1965, artist: 'Sonny Wern & Still Loud', title: 'I Like To Move It (Muévelo) [with Daddy Yankee] (feat. Daddy Yankee)', genre: 'EDM', votes: 0 },
    { id: 1966, artist: 'Sound Of Legend', title: 'Moonlight Shadow', genre: 'EDM', votes: 0 },
    { id: 1967, artist: 'Sound Of Legend, Groove Coverage & DJane HouseKat', title: 'God Is A Girl', genre: 'EDM', votes: 0 },
    { id: 1968, artist: 'Swedish House Mafia & Alicia Keys', title: 'Finally', genre: 'EDM', votes: 0 },
    { id: 1969, artist: 'Swedish House Mafia & Niki & The Dove', title: 'Lioness', genre: 'EDM', votes: 0 },
    { id: 1970, artist: 'Swedish House Mafia', title: 'Wait So Long (Why Do I Have To)', genre: 'EDM', votes: 0 },
    { id: 1971, artist: 'Switch Disco, R3HAB & Sam Feldt', title: 'SLEEP TONIGHT (THIS IS THE LIFE)', genre: 'EDM', votes: 0 },
    { id: 1972, artist: 'TELYKAST & Moa Lisa', title: 'Feel Again', genre: 'EDM', votes: 0 },
    { id: 1973, artist: 'Ten Crazy Brothers & Luka Maric', title: 'Save Your Tears - Dance Mix', genre: 'EDM', votes: 0 },
    { id: 1974, artist: 'Ten Crazy Brothers', title: 'Bloody Mary', genre: 'EDM', votes: 0 },
    { id: 1975, artist: 'The Chemical Brothers & ARTBAT', title: 'Hey Boy Hey Girl (ARTBAT Remix)', genre: 'EDM', votes: 0 },
    { id: 1976, artist: 'The Stickmen Project & Sadie Rose Van', title: 'Circles (feat. Sadie Rose Van)', genre: 'EDM', votes: 0 },
    { id: 1977, artist: 'Tiësto', title: 'I Follow Rivers (feat. Oaks)', genre: 'EDM', votes: 0 },
    { id: 1978, artist: 'Tiësto', title: 'Lethal Industry (Rose Ringed Remix)', genre: 'EDM', votes: 0 },
    { id: 1979, artist: 'Tiësto, Odd Mob & Goodboys', title: 'Won’t Be Possible', genre: 'EDM', votes: 0 },
    { id: 1980, artist: 'TOCHIMON', title: 'Falling (feat. Kelo) (feat. Kelo)', genre: 'EDM', votes: 0 },
    { id: 1981, artist: 'TOCHIMON', title: 'Heartbeat', genre: 'EDM', votes: 0 },
    { id: 1982, artist: 'Trinix & One-T', title: 'The Magic Key', genre: 'EDM', votes: 0 },
    { id: 1983, artist: 'TWINSICK', title: 'Happy Now', genre: 'EDM', votes: 0 },
    { id: 1984, artist: 'twocolors & Roe Byrne', title: 'Stereo', genre: 'EDM', votes: 0 },
    { id: 1985, artist: 'twocolors, Safri Duo & Chris de Sarandy', title: 'Cynical', genre: 'EDM', votes: 0 },
    { id: 1986, artist: 'Unknown Artist', title: 'unnamed', genre: 'EDM', votes: 0 },
    { id: 1987, artist: 'Upsilone & Astrid James', title: 'Everytime We Touch', genre: 'EDM', votes: 0 },
    { id: 1988, artist: 'Zani Mitmar & Planet Wave House', title: 'Promise', genre: 'EDM', votes: 0 },
    { id: 1989, artist: 'Zani Mitmar', title: 'The One For Me (Radio)', genre: 'EDM', votes: 0 },
    { id: 1990, artist: 'Zouchy', title: 'This Moment', genre: 'EDM', votes: 0 }];

